{{-- include_area_app_common_start --}}
@include('apples._common'){{-- generated by scaffold - Apple --}}
@include('apples._common'){{-- generated by scaffold - Apple --}}
@include('apples._common'){{-- generated by scaffold - Apple --}}
@include('apples._common'){{-- generated by scaffold - Apple --}}
@include('apples._common'){{-- generated by scaffold - Apple --}}
@include('menus._common'){{-- generated by scaffold - Menu --}}
@include('banderas._common'){{-- generated by scaffold - Bandera --}}
@include('lectivos._common'){{-- generated by scaffold - Lectivo --}}
@include('menus._common'){{-- generated by scaffold - Menu --}}
@include('plantels._common'){{-- generated by scaffold - Plantel --}}
@include('banderas._common'){{-- generated by scaffold - Bandera --}}
@include('lectivos._common'){{-- generated by scaffold - Lectivo --}}
@include('plantels._common'){{-- generated by scaffold - Plantel --}}
@include('areas._common'){{-- generated by scaffold - Area --}}
@include('puestos._common'){{-- generated by scaffold - Puesto --}}
@include('stPuestos._common'){{-- generated by scaffold - StPuesto --}}
@include('empleados._common'){{-- generated by scaffold - Empleado --}}
@include('stEmpleados._common'){{-- generated by scaffold - StEmpleado --}}
@include('stClientes._common'){{-- generated by scaffold - StCliente --}}
@include('ofertas._common'){{-- generated by scaffold - Ofertum --}}
@include('medios._common'){{-- generated by scaffold - Medio --}}
@include('tareas._common'){{-- generated by scaffold - Tarea --}}
@include('estados._common'){{-- generated by scaffold - Estado --}}
@include('municipios._common'){{-- generated by scaffold - Municipio --}}
@include('clientes._common'){{-- generated by scaffold - Cliente --}}
@include('preguntas._common'){{-- generated by scaffold - Preguntum --}}
@include('preguntaClientes._common'){{-- generated by scaffold - PreguntaCliente --}}
@include('periodos._common'){{-- generated by scaffold - Periodo --}}
@include('plantillas._common'){{-- generated by scaffold - Plantilla --}}
@include('nivels._common'){{-- generated by scaffold - Nivel --}}
@include('grados._common'){{-- generated by scaffold - Grado --}}
@include('cursos._common'){{-- generated by scaffold - Curso --}}
@include('subcursos._common'){{-- generated by scaffold - Subcurso --}}
@include('diplomados._common'){{-- generated by scaffold - Diplomado --}}
@include('subdiplomados._common'){{-- generated by scaffold - Subdiplomado --}}
@include('otros._common'){{-- generated by scaffold - Otro --}}
@include('subotros._common'){{-- generated by scaffold - Subotro --}}
@include('promocions._common'){{-- generated by scaffold - Promocion --}}
@include('tpoCorreos._common'){{-- generated by scaffold - TpoCorreo --}}
@include('sms._common'){{-- generated by scaffold - Sm --}}
@include('correos._common'){{-- generated by scaffold - Correo --}}
@include('params._common'){{-- generated by scaffold - Param --}}
@include('stTareas._common'){{-- generated by scaffold - StTarea --}}
@include('asignacionTareas._common'){{-- generated by scaffold - AsignacionTarea --}}
@include('asignacionTareas._common'){{-- generated by scaffold - AsignacionTarea --}}
@include('seguimientoTareas._common'){{-- generated by scaffold - SeguimientoTarea --}}
@include('asignacionTareas._common'){{-- generated by scaffold - AsignacionTarea --}}
@include('asuntos._common'){{-- generated by scaffold - Asunto --}}
@include('tpoPlantels._common'){{-- generated by scaffold - TpoPlantel --}}
@include('especialidads._common'){{-- generated by scaffold - Especialidad --}}
@include('seguimientos._common'){{-- generated by scaffold - Seguimiento --}}
@include('stSeguimientos._common'){{-- generated by scaffold - StSeguimiento --}}
@include('avisos._common'){{-- generated by scaffold - Aviso --}}
@include('cambioStSeguimientos._common'){{-- generated by scaffold - CambioStSeguimiento --}}
@include('avisoGrals._common'){{-- generated by scaffold - AvisoGral --}}
@include('avisoGrals._common'){{-- generated by scaffold - AvisoGral --}}
@include('docEmpleados._common'){{-- generated by scaffold - DocEmpleado --}}
@include('pivotDocEmpleados._common'){{-- generated by scaffold - PivotDocEmpleado --}}
@include('pivotAvisoGralEmpleados._common'){{-- generated by scaffold - PivotAvisoGralEmpleado --}}
@include('asuntos._common'){{-- generated by scaffold - Asunto --}}
@include('alumnos._common'){{-- generated by scaffold - Alumno --}}
@include('jornadas._common'){{-- generated by scaffold - Jornada --}}
@include('salons._common'){{-- generated by scaffold - Salon --}}
@include('periodos._common'){{-- generated by scaffold - Periodo --}}
@include('periodoEstudios._common'){{-- generated by scaffold - PeriodoEstudio --}}
@include('grupos._common'){{-- generated by scaffold - Grupo --}}
@include('materias._common'){{-- generated by scaffold - Materium --}}
@include('stAlumnos._common'){{-- generated by scaffold - StAlumno --}}
@include('inscripcions._common'){{-- generated by scaffold - Inscripcion --}}
@include('docAlumnos._common'){{-- generated by scaffold - DocAlumno --}}
@include('stPlantels._common'){{-- generated by scaffold - StPlantel --}}
@include('dias._common'){{-- generated by scaffold - Dium --}}
@include('asignacionAcademicas._common'){{-- generated by scaffold - AsignacionAcademica --}}
@include('horarios._common'){{-- generated by scaffold - Horario --}}
@include('stMaterias._common'){{-- generated by scaffold - StMateria --}}
@include('tpoExamens._common'){{-- generated by scaffold - TpoExaman --}}
@include('hacademicas._common'){{-- generated by scaffold - Hacademica --}}
@include('calificacions._common'){{-- generated by scaffold - Calificacion --}}
@include('ponderacions._common'){{-- generated by scaffold - Ponderacion --}}
@include('cargaPonderacions._common'){{-- generated by scaffold - CargaPonderacion --}}
@include('calificacionPonderacions._common'){{-- generated by scaffold - CalificacionPonderacion --}}
@include('hsSeguimientos._common'){{-- generated by scaffold - HsSeguimiento --}}
@include('calendarioEvaluacions._common'){{-- generated by scaffold - CalendarioEvaluacion --}}
@include('asuntos._common'){{-- generated by scaffold - Asunto --}}
@include('giros._common'){{-- generated by scaffold - Giro --}}
@include('empresas._common'){{-- generated by scaffold - Empresa --}}
@include('asistenciasCs._common'){{-- generated by scaffold - AsistenciasC --}}
@include('estAsistencias._common'){{-- generated by scaffold - EstAsistencium --}}
@include('asistenciaRs._common'){{-- generated by scaffold - AsistenciaR --}}
@include('modulos._common'){{-- generated by scaffold - Modulo --}}
@include('grupoPeriodoEstudios._common'){{-- generated by scaffold - GrupoPeriodoEstudio --}}
@include('materiumPeriodos._common'){{-- generated by scaffold - MateriumPeriodo --}}
@include('actividadEmpresas._common'){{-- generated by scaffold - ActividadEmpresa --}}
@include('actividadEmpresas._common'){{-- generated by scaffold - ActividadEmpresa --}}
@include('combinacionEmpresas._common'){{-- generated by scaffold - CombinacionEmpresa --}}
@include('stCuestionarios._common'){{-- generated by scaffold - StCuestionario --}}
@include('cuestionarios._common'){{-- generated by scaffold - Cuestionario --}}
@include('cuestionarioPreguntas._common'){{-- generated by scaffold - CuestionarioPregunta --}}
@include('cuestionarioRespuestas._common'){{-- generated by scaffold - CuestionarioRespuesta --}}
@include('cuestionarioDatos._common'){{-- generated by scaffold - CuestionarioDato --}}
@include('combinacionClientes._common'){{-- generated by scaffold - CombinacionCliente --}}
@include('combinacionClientes._common'){{-- generated by scaffold - CombinacionCliente --}}
@include('combinacionClientes._common'){{-- generated by scaffold - CombinacionCliente --}}
@include('diaNoHabils._common'){{-- generated by scaffold - DiaNoHabil --}}
@include('diaNoHabils._common'){{-- generated by scaffold - DiaNoHabil --}}
@include('ccuestionarios._common'){{-- generated by scaffold - Ccuestionario --}}
@include('ccuestionarioPreguntas._common'){{-- generated by scaffold - CcuestionarioPreguntum --}}
@include('ccuestionarioRespuestas._common'){{-- generated by scaffold - CcuestionarioRespuestum --}}
@include('ccuestionarioDatos._common'){{-- generated by scaffold - CcuestionarioDato --}}
@include('pagosLectivos._common'){{-- generated by scaffold - PagosLectivo --}}
@include('cuentaContables._common'){{-- generated by scaffold - CuentaContable --}}
@include('reglaRecargos._common'){{-- generated by scaffold - ReglaRecargo --}}
@include('pagosLectivosLns._common'){{-- generated by scaffold - PagosLectivosLn --}}
@include('planCampoFiltros._common'){{-- generated by scaffold - PlanCampoFiltro --}}
@include('planCondicionFiltros._common'){{-- generated by scaffold - PlanCondicionFiltro --}}
@include('tpoInformes._common'){{-- generated by scaffold - TpoInforme --}}
@include('avisosInicios._common'){{-- generated by scaffold - AvisosInicio --}}
@include('smsPredefinidos._common'){{-- generated by scaffold - SmsPredefinido --}}
@include('cajaConceptos._common'){{-- generated by scaffold - CajaConcepto --}}
@include('cuentaContables._common'){{-- generated by scaffold - CuentaContable --}}
@include('planPagos._common'){{-- generated by scaffold - PlanPago --}}
@include('planPagoLns._common'){{-- generated by scaffold - PlanPagoLn --}}
@include('formaPagos._common'){{-- generated by scaffold - FormaPago --}}
@include('reglaRecargos._common'){{-- generated by scaffold - ReglaRecargo --}}
@include('tipoReglas._common'){{-- generated by scaffold - TipoRegla --}}
@include('adeudos._common'){{-- generated by scaffold - Adeudo --}}
@include('cajas._common'){{-- generated by scaffold - Caja --}}
@include('cajaLns._common'){{-- generated by scaffold - CajaLn --}}
@include('stCajas._common'){{-- generated by scaffold - StCaja --}}
@include('segmentoMercados._common'){{-- generated by scaffold - SegmentoMercado --}}
@include('pagos._common'){{-- generated by scaffold - Pago --}}
@include('pagos._common'){{-- generated by scaffold - Pago --}}
@include('paises._common'){{-- generated by scaffold - Paise --}}
@include('historiaEventos._common'){{-- generated by scaffold - HistoriaEvento --}}
@include('historials._common'){{-- generated by scaffold - Historial --}}
@include('ebanxes._common'){{-- generated by scaffold - Ebanx --}}
@include('promocions._common'){{-- generated by scaffold - Promocion --}}
@include('promoPlanLns._common'){{-- generated by scaffold - PromoPlanLn --}}
@include('stEmpresas._common'){{-- generated by scaffold - StEmpresa --}}
@include('tareasEmpresas._common'){{-- generated by scaffold - TareasEmpresa --}}
@include('avisosEmpresas._common'){{-- generated by scaffold - AvisosEmpresa --}}
@include('mese._common'){{-- generated by scaffold - Mese --}}
@include('stBecas._common'){{-- generated by scaffold - StBeca --}}
@include('autorizacionBecas._common'){{-- generated by scaffold - AutorizacionBeca --}}
@include('autorizacionBecaComentarios._common'){{-- generated by scaffold - AutorizacionBecaComentario --}}
@include('cursos._common'){{-- generated by scaffold - Curso --}}
@include('cursosEmpresas._common'){{-- generated by scaffold - CursosEmpresa --}}
@include('stCursoEmpresas._common'){{-- generated by scaffold - StCursoEmpresa --}}
@include('cursosEmpresas._common'){{-- generated by scaffold - CursosEmpresa --}}
@include('cotizacionCursos._common'){{-- generated by scaffold - CotizacionCurso --}}
@include('tipoPrecioCotis._common'){{-- generated by scaffold - TipoPrecioCoti --}}
@include('cotizacionLns._common'){{-- generated by scaffold - CotizacionLn --}}
@include('facturaCotizacions._common'){{-- generated by scaffold - FacturaCotizacion --}}
@include('stInscripcions._common'){{-- generated by scaffold - StInscripcion --}}
@include('consultaCalificacions._common'){{-- generated by scaffold - ConsultaCalificacion --}}
@include('eventoClientes._common'){{-- generated by scaffold - EventoCliente --}}
@include('historiaClientes._common'){{-- generated by scaffold - HistoriaCliente --}}
@include('cuentasEfectivos._common'){{-- generated by scaffold - CuentasEfectivo --}}
@include('egresosConceptos._common'){{-- generated by scaffold - EgresosConcepto --}}
@include('asuntos._common'){{-- generated by scaffold - Asunto --}}
@include('egresos._common'){{-- generated by scaffold - Egreso --}}
@include('cuentasEfectivoPlantels._common'){{-- generated by scaffold - CuentasEfectivoPlantel --}}
@include('hCuentasEfectivos._common'){{-- generated by scaffold - HCuentasEfectivo --}}
@include('ingresoEgresos._common'){{-- generated by scaffold - IngresoEgreso --}}
@include('transferences._common'){{-- generated by scaffold - Transference --}}
@include('transferences._common'){{-- generated by scaffold - Transference --}}
@include('hEstatuses._common'){{-- generated by scaffold - HEstatus --}}
@include('docPlantels._common'){{-- generated by scaffold - DocPlantel --}}
@include('docPlantelPlantels._common'){{-- generated by scaffold - DocPlantelPlantel --}}
@include('vinculacions._common'){{-- generated by scaffold - Vinculacion --}}
@include('vinculacions._common'){{-- generated by scaffold - Vinculacion --}}
@include('vinculacionHoras._common'){{-- generated by scaffold - VinculacionHora --}}
@include('docVinculacions._common'){{-- generated by scaffold - DocVinculacion --}}
@include('docVinculacionVinculacions._common'){{-- generated by scaffold - DocVinculacionVinculacion --}}
@include('escolaridads._common'){{-- generated by scaffold - Escolaridad --}}
@include('unidadUsos._common'){{-- generated by scaffold - UnidadUso --}}
@include('categoriaArticulos._common'){{-- generated by scaffold - CategoriaArticulo --}}
@include('articulos._common'){{-- generated by scaffold - Articulo --}}
@include('entradaSalidas._common'){{-- generated by scaffold - EntradaSalida --}}
@include('existencias._common'){{-- generated by scaffold - Existencium --}}
@include('movimientos._common'){{-- generated by scaffold - Movimiento --}}
@include('plantillaEmpresas._common'){{-- generated by scaffold - PlantillaEmpresa --}}
@include('plantillaEmpresaCampos._common'){{-- generated by scaffold - PlantillaEmpresaCampo --}}
@include('plantillaEmpresaConds._common'){{-- generated by scaffold - PlantillaEmpresaCond --}}
@include('ubicacionArts._common'){{-- generated by scaffold - UbicacionArt --}}
@include('tpoArticulos._common'){{-- generated by scaffold - TpoArticulo --}}
{{-- include_area_app_common_end --}}

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu level 1<span class="caret"></span></a>
                        <ul id="app_navi" class="dropdown-menu" role="menu">
                        <li{!! Request::is('apples*') ? ' class="active"' : '' !!}><a href="/apples/">@yield('applesAppTitle')</a></li>{{-- generated by scaffold - Apple --}}
                        <li{!! Request::is('apples*') ? ' class="active"' : '' !!}><a href="/apples/">@yield('applesAppTitle')</a></li>{{-- generated by scaffold - Apple --}}
                        <li{!! Request::is('apples*') ? ' class="active"' : '' !!}><a href="/apples/">@yield('applesAppTitle')</a></li>{{-- generated by scaffold - Apple --}}
                        <li{!! Request::is('apples*') ? ' class="active"' : '' !!}><a href="/apples/">@yield('applesAppTitle')</a></li>{{-- generated by scaffold - Apple --}}
                        <li{!! Request::is('apples*') ? ' class="active"' : '' !!}><a href="/apples/">@yield('applesAppTitle')</a></li>{{-- generated by scaffold - Apple --}}
                        <li{!! Request::is('menus*') ? ' class="active"' : '' !!}><a href="/menus/">@yield('menusAppTitle')</a></li>{{-- generated by scaffold - Menu --}}
                        <li{!! Request::is('banderas*') ? ' class="active"' : '' !!}><a href="/banderas/">@yield('banderasAppTitle')</a></li>{{-- generated by scaffold - Bandera --}}
                        <li{!! Request::is('lectivos*') ? ' class="active"' : '' !!}><a href="/lectivos/">@yield('lectivosAppTitle')</a></li>{{-- generated by scaffold - Lectivo --}}
                        <li{!! Request::is('menus*') ? ' class="active"' : '' !!}><a href="/menus/">@yield('menusAppTitle')</a></li>{{-- generated by scaffold - Menu --}}
                        <li{!! Request::is('plantels*') ? ' class="active"' : '' !!}><a href="/plantels/">@yield('plantelsAppTitle')</a></li>{{-- generated by scaffold - Plantel --}}
                        <li{!! Request::is('banderas*') ? ' class="active"' : '' !!}><a href="/banderas/">@yield('banderasAppTitle')</a></li>{{-- generated by scaffold - Bandera --}}
                        <li{!! Request::is('lectivos*') ? ' class="active"' : '' !!}><a href="/lectivos/">@yield('lectivosAppTitle')</a></li>{{-- generated by scaffold - Lectivo --}}
                        <li{!! Request::is('plantels*') ? ' class="active"' : '' !!}><a href="/plantels/">@yield('plantelsAppTitle')</a></li>{{-- generated by scaffold - Plantel --}}
                        <li{!! Request::is('areas*') ? ' class="active"' : '' !!}><a href="/areas/">@yield('areasAppTitle')</a></li>{{-- generated by scaffold - Area --}}
                        <li{!! Request::is('puestos*') ? ' class="active"' : '' !!}><a href="/puestos/">@yield('puestosAppTitle')</a></li>{{-- generated by scaffold - Puesto --}}
                        <li{!! Request::is('stPuestos*') ? ' class="active"' : '' !!}><a href="/stPuestos/">@yield('stPuestosAppTitle')</a></li>{{-- generated by scaffold - StPuesto --}}
                        <li{!! Request::is('empleados*') ? ' class="active"' : '' !!}><a href="/empleados/">@yield('empleadosAppTitle')</a></li>{{-- generated by scaffold - Empleado --}}
                        <li{!! Request::is('stEmpleados*') ? ' class="active"' : '' !!}><a href="/stEmpleados/">@yield('stEmpleadosAppTitle')</a></li>{{-- generated by scaffold - StEmpleado --}}
                        <li{!! Request::is('stClientes*') ? ' class="active"' : '' !!}><a href="/stClientes/">@yield('stClientesAppTitle')</a></li>{{-- generated by scaffold - StCliente --}}
                        <li{!! Request::is('ofertas*') ? ' class="active"' : '' !!}><a href="/ofertas/">@yield('ofertasAppTitle')</a></li>{{-- generated by scaffold - Ofertum --}}
                        <li{!! Request::is('medios*') ? ' class="active"' : '' !!}><a href="/medios/">@yield('mediosAppTitle')</a></li>{{-- generated by scaffold - Medio --}}
                        <li{!! Request::is('tareas*') ? ' class="active"' : '' !!}><a href="/tareas/">@yield('tareasAppTitle')</a></li>{{-- generated by scaffold - Tarea --}}
                        <li{!! Request::is('estados*') ? ' class="active"' : '' !!}><a href="/estados/">@yield('estadosAppTitle')</a></li>{{-- generated by scaffold - Estado --}}
                        <li{!! Request::is('municipios*') ? ' class="active"' : '' !!}><a href="/municipios/">@yield('municipiosAppTitle')</a></li>{{-- generated by scaffold - Municipio --}}
                        <li{!! Request::is('clientes*') ? ' class="active"' : '' !!}><a href="/clientes/">@yield('clientesAppTitle')</a></li>{{-- generated by scaffold - Cliente --}}
                        <li{!! Request::is('preguntas*') ? ' class="active"' : '' !!}><a href="/preguntas/">@yield('preguntasAppTitle')</a></li>{{-- generated by scaffold - Preguntum --}}
                        <li{!! Request::is('preguntaClientes*') ? ' class="active"' : '' !!}><a href="/preguntaClientes/">@yield('preguntaClientesAppTitle')</a></li>{{-- generated by scaffold - PreguntaCliente --}}
                        <li{!! Request::is('periodos*') ? ' class="active"' : '' !!}><a href="/periodos/">@yield('periodosAppTitle')</a></li>{{-- generated by scaffold - Periodo --}}
                        <li{!! Request::is('plantillas*') ? ' class="active"' : '' !!}><a href="/plantillas/">@yield('plantillasAppTitle')</a></li>{{-- generated by scaffold - Plantilla --}}
                        <li{!! Request::is('nivels*') ? ' class="active"' : '' !!}><a href="/nivels/">@yield('nivelsAppTitle')</a></li>{{-- generated by scaffold - Nivel --}}
                        <li{!! Request::is('grados*') ? ' class="active"' : '' !!}><a href="/grados/">@yield('gradosAppTitle')</a></li>{{-- generated by scaffold - Grado --}}
                        <li{!! Request::is('cursos*') ? ' class="active"' : '' !!}><a href="/cursos/">@yield('cursosAppTitle')</a></li>{{-- generated by scaffold - Curso --}}
                        <li{!! Request::is('subcursos*') ? ' class="active"' : '' !!}><a href="/subcursos/">@yield('subcursosAppTitle')</a></li>{{-- generated by scaffold - Subcurso --}}
                        <li{!! Request::is('diplomados*') ? ' class="active"' : '' !!}><a href="/diplomados/">@yield('diplomadosAppTitle')</a></li>{{-- generated by scaffold - Diplomado --}}
                        <li{!! Request::is('subdiplomados*') ? ' class="active"' : '' !!}><a href="/subdiplomados/">@yield('subdiplomadosAppTitle')</a></li>{{-- generated by scaffold - Subdiplomado --}}
                        <li{!! Request::is('otros*') ? ' class="active"' : '' !!}><a href="/otros/">@yield('otrosAppTitle')</a></li>{{-- generated by scaffold - Otro --}}
                        <li{!! Request::is('subotros*') ? ' class="active"' : '' !!}><a href="/subotros/">@yield('subotrosAppTitle')</a></li>{{-- generated by scaffold - Subotro --}}
                        <li{!! Request::is('promocions*') ? ' class="active"' : '' !!}><a href="/promocions/">@yield('promocionsAppTitle')</a></li>{{-- generated by scaffold - Promocion --}}
                        <li{!! Request::is('tpoCorreos*') ? ' class="active"' : '' !!}><a href="/tpoCorreos/">@yield('tpoCorreosAppTitle')</a></li>{{-- generated by scaffold - TpoCorreo --}}
                        <li{!! Request::is('sms*') ? ' class="active"' : '' !!}><a href="/sms/">@yield('smsAppTitle')</a></li>{{-- generated by scaffold - Sm --}}
                        <li{!! Request::is('correos*') ? ' class="active"' : '' !!}><a href="/correos/">@yield('correosAppTitle')</a></li>{{-- generated by scaffold - Correo --}}
                        <li{!! Request::is('params*') ? ' class="active"' : '' !!}><a href="/params/">@yield('paramsAppTitle')</a></li>{{-- generated by scaffold - Param --}}
                        <li{!! Request::is('stTareas*') ? ' class="active"' : '' !!}><a href="/stTareas/">@yield('stTareasAppTitle')</a></li>{{-- generated by scaffold - StTarea --}}
                        <li{!! Request::is('asignacionTareas*') ? ' class="active"' : '' !!}><a href="/asignacionTareas/">@yield('asignacionTareasAppTitle')</a></li>{{-- generated by scaffold - AsignacionTarea --}}
                        <li{!! Request::is('seguimientoTareas*') ? ' class="active"' : '' !!}><a href="/seguimientoTareas/">@yield('seguimientoTareasAppTitle')</a></li>{{-- generated by scaffold - SeguimientoTarea --}}
                        <li{!! Request::is('asuntos*') ? ' class="active"' : '' !!}><a href="/asuntos/">@yield('asuntosAppTitle')</a></li>{{-- generated by scaffold - Asunto --}}
                        <li{!! Request::is('tpoPlantels*') ? ' class="active"' : '' !!}><a href="/tpoPlantels/">@yield('tpoPlantelsAppTitle')</a></li>{{-- generated by scaffold - TpoPlantel --}}
                        <li{!! Request::is('especialidads*') ? ' class="active"' : '' !!}><a href="/especialidads/">@yield('especialidadsAppTitle')</a></li>{{-- generated by scaffold - Especialidad --}}
                        <li{!! Request::is('seguimientos*') ? ' class="active"' : '' !!}><a href="/seguimientos/">@yield('seguimientosAppTitle')</a></li>{{-- generated by scaffold - Seguimiento --}}
                        <li{!! Request::is('stSeguimientos*') ? ' class="active"' : '' !!}><a href="/stSeguimientos/">@yield('stSeguimientosAppTitle')</a></li>{{-- generated by scaffold - StSeguimiento --}}
                        <li{!! Request::is('avisos*') ? ' class="active"' : '' !!}><a href="/avisos/">@yield('avisosAppTitle')</a></li>{{-- generated by scaffold - Aviso --}}
                        <li{!! Request::is('cambioStSeguimientos*') ? ' class="active"' : '' !!}><a href="/cambioStSeguimientos/">@yield('cambioStSeguimientosAppTitle')</a></li>{{-- generated by scaffold - CambioStSeguimiento --}}
                        <li{!! Request::is('avisoGrals*') ? ' class="active"' : '' !!}><a href="/avisoGrals/">@yield('avisoGralsAppTitle')</a></li>{{-- generated by scaffold - AvisoGral --}}
                        <li{!! Request::is('avisoGrals*') ? ' class="active"' : '' !!}><a href="/avisoGrals/">@yield('avisoGralsAppTitle')</a></li>{{-- generated by scaffold - AvisoGral --}}
                        <li{!! Request::is('docEmpleados*') ? ' class="active"' : '' !!}><a href="/docEmpleados/">@yield('docEmpleadosAppTitle')</a></li>{{-- generated by scaffold - DocEmpleado --}}
                        <li{!! Request::is('pivotDocEmpleados*') ? ' class="active"' : '' !!}><a href="/pivotDocEmpleados/">@yield('pivotDocEmpleadosAppTitle')</a></li>{{-- generated by scaffold - PivotDocEmpleado --}}
                        <li{!! Request::is('pivotAvisoGralEmpleados*') ? ' class="active"' : '' !!}><a href="/pivotAvisoGralEmpleados/">@yield('pivotAvisoGralEmpleadosAppTitle')</a></li>{{-- generated by scaffold - PivotAvisoGralEmpleado --}}
                        <li{!! Request::is('asuntos*') ? ' class="active"' : '' !!}><a href="/asuntos/">@yield('asuntosAppTitle')</a></li>{{-- generated by scaffold - Asunto --}}
                        <li{!! Request::is('alumnos*') ? ' class="active"' : '' !!}><a href="/alumnos/">@yield('alumnosAppTitle')</a></li>{{-- generated by scaffold - Alumno --}}
                        <li{!! Request::is('jornadas*') ? ' class="active"' : '' !!}><a href="/jornadas/">@yield('jornadasAppTitle')</a></li>{{-- generated by scaffold - Jornada --}}
                        <li{!! Request::is('salons*') ? ' class="active"' : '' !!}><a href="/salons/">@yield('salonsAppTitle')</a></li>{{-- generated by scaffold - Salon --}}
                        <li{!! Request::is('periodos*') ? ' class="active"' : '' !!}><a href="/periodos/">@yield('periodosAppTitle')</a></li>{{-- generated by scaffold - Periodo --}}
                        <li{!! Request::is('periodoEstudios*') ? ' class="active"' : '' !!}><a href="/periodoEstudios/">@yield('periodoEstudiosAppTitle')</a></li>{{-- generated by scaffold - PeriodoEstudio --}}
                        <li{!! Request::is('grupos*') ? ' class="active"' : '' !!}><a href="/grupos/">@yield('gruposAppTitle')</a></li>{{-- generated by scaffold - Grupo --}}
                        <li{!! Request::is('materias*') ? ' class="active"' : '' !!}><a href="/materias/">@yield('materiasAppTitle')</a></li>{{-- generated by scaffold - Materium --}}
                        <li{!! Request::is('stAlumnos*') ? ' class="active"' : '' !!}><a href="/stAlumnos/">@yield('stAlumnosAppTitle')</a></li>{{-- generated by scaffold - StAlumno --}}
                        <li{!! Request::is('inscripcions*') ? ' class="active"' : '' !!}><a href="/inscripcions/">@yield('inscripcionsAppTitle')</a></li>{{-- generated by scaffold - Inscripcion --}}
                        <li{!! Request::is('docAlumnos*') ? ' class="active"' : '' !!}><a href="/docAlumnos/">@yield('docAlumnosAppTitle')</a></li>{{-- generated by scaffold - DocAlumno --}}
                        <li{!! Request::is('stPlantels*') ? ' class="active"' : '' !!}><a href="/stPlantels/">@yield('stPlantelsAppTitle')</a></li>{{-- generated by scaffold - StPlantel --}}
                        <li{!! Request::is('dias*') ? ' class="active"' : '' !!}><a href="/dias/">@yield('diasAppTitle')</a></li>{{-- generated by scaffold - Dium --}}
                        <li{!! Request::is('asignacionAcademicas*') ? ' class="active"' : '' !!}><a href="/asignacionAcademicas/">@yield('asignacionAcademicasAppTitle')</a></li>{{-- generated by scaffold - AsignacionAcademica --}}
                        <li{!! Request::is('horarios*') ? ' class="active"' : '' !!}><a href="/horarios/">@yield('horariosAppTitle')</a></li>{{-- generated by scaffold - Horario --}}
                        <li{!! Request::is('stMaterias*') ? ' class="active"' : '' !!}><a href="/stMaterias/">@yield('stMateriasAppTitle')</a></li>{{-- generated by scaffold - StMateria --}}
                        <li{!! Request::is('tpoExamens*') ? ' class="active"' : '' !!}><a href="/tpoExamens/">@yield('tpoExamensAppTitle')</a></li>{{-- generated by scaffold - TpoExaman --}}
                        <li{!! Request::is('hacademicas*') ? ' class="active"' : '' !!}><a href="/hacademicas/">@yield('hacademicasAppTitle')</a></li>{{-- generated by scaffold - Hacademica --}}
                        <li{!! Request::is('calificacions*') ? ' class="active"' : '' !!}><a href="/calificacions/">@yield('calificacionsAppTitle')</a></li>{{-- generated by scaffold - Calificacion --}}
                        <li{!! Request::is('ponderacions*') ? ' class="active"' : '' !!}><a href="/ponderacions/">@yield('ponderacionsAppTitle')</a></li>{{-- generated by scaffold - Ponderacion --}}
                        <li{!! Request::is('cargaPonderacions*') ? ' class="active"' : '' !!}><a href="/cargaPonderacions/">@yield('cargaPonderacionsAppTitle')</a></li>{{-- generated by scaffold - CargaPonderacion --}}
                        <li{!! Request::is('calificacionPonderacions*') ? ' class="active"' : '' !!}><a href="/calificacionPonderacions/">@yield('calificacionPonderacionsAppTitle')</a></li>{{-- generated by scaffold - CalificacionPonderacion --}}
                        <li{!! Request::is('hsSeguimientos*') ? ' class="active"' : '' !!}><a href="/hsSeguimientos/">@yield('hsSeguimientosAppTitle')</a></li>{{-- generated by scaffold - HsSeguimiento --}}
                        <li{!! Request::is('calendarioEvaluacions*') ? ' class="active"' : '' !!}><a href="/calendarioEvaluacions/">@yield('calendarioEvaluacionsAppTitle')</a></li>{{-- generated by scaffold - CalendarioEvaluacion --}}
                        <li{!! Request::is('asuntos*') ? ' class="active"' : '' !!}><a href="/asuntos/">@yield('asuntosAppTitle')</a></li>{{-- generated by scaffold - Asunto --}}
                        <li{!! Request::is('giros*') ? ' class="active"' : '' !!}><a href="/giros/">@yield('girosAppTitle')</a></li>{{-- generated by scaffold - Giro --}}
                        <li{!! Request::is('empresas*') ? ' class="active"' : '' !!}><a href="/empresas/">@yield('empresasAppTitle')</a></li>{{-- generated by scaffold - Empresa --}}
                        <li{!! Request::is('asistenciasCs*') ? ' class="active"' : '' !!}><a href="/asistenciasCs/">@yield('asistenciasCsAppTitle')</a></li>{{-- generated by scaffold - AsistenciasC --}}
                        <li{!! Request::is('estAsistencias*') ? ' class="active"' : '' !!}><a href="/estAsistencias/">@yield('estAsistenciasAppTitle')</a></li>{{-- generated by scaffold - EstAsistencium --}}
                        <li{!! Request::is('asistenciaRs*') ? ' class="active"' : '' !!}><a href="/asistenciaRs/">@yield('asistenciaRsAppTitle')</a></li>{{-- generated by scaffold - AsistenciaR --}}
                        <li{!! Request::is('modulos*') ? ' class="active"' : '' !!}><a href="/modulos/">@yield('modulosAppTitle')</a></li>{{-- generated by scaffold - Modulo --}}
                        <li{!! Request::is('grupoPeriodoEstudios*') ? ' class="active"' : '' !!}><a href="/grupoPeriodoEstudios/">@yield('grupoPeriodoEstudiosAppTitle')</a></li>{{-- generated by scaffold - GrupoPeriodoEstudio --}}
                        <li{!! Request::is('materiumPeriodos*') ? ' class="active"' : '' !!}><a href="/materiumPeriodos/">@yield('materiumPeriodosAppTitle')</a></li>{{-- generated by scaffold - MateriumPeriodo --}}
                        <li{!! Request::is('actividadEmpresas*') ? ' class="active"' : '' !!}><a href="/actividadEmpresas/">@yield('actividadEmpresasAppTitle')</a></li>{{-- generated by scaffold - ActividadEmpresa --}}
                        <li{!! Request::is('actividadEmpresas*') ? ' class="active"' : '' !!}><a href="/actividadEmpresas/">@yield('actividadEmpresasAppTitle')</a></li>{{-- generated by scaffold - ActividadEmpresa --}}
                        <li{!! Request::is('combinacionEmpresas*') ? ' class="active"' : '' !!}><a href="/combinacionEmpresas/">@yield('combinacionEmpresasAppTitle')</a></li>{{-- generated by scaffold - CombinacionEmpresa --}}
                        <li{!! Request::is('stCuestionarios*') ? ' class="active"' : '' !!}><a href="/stCuestionarios/">@yield('stCuestionariosAppTitle')</a></li>{{-- generated by scaffold - StCuestionario --}}
                        <li{!! Request::is('cuestionarios*') ? ' class="active"' : '' !!}><a href="/cuestionarios/">@yield('cuestionariosAppTitle')</a></li>{{-- generated by scaffold - Cuestionario --}}
                        <li{!! Request::is('cuestionarioPreguntas*') ? ' class="active"' : '' !!}><a href="/cuestionarioPreguntas/">@yield('cuestionarioPreguntasAppTitle')</a></li>{{-- generated by scaffold - CuestionarioPregunta --}}
                        <li{!! Request::is('cuestionarioRespuestas*') ? ' class="active"' : '' !!}><a href="/cuestionarioRespuestas/">@yield('cuestionarioRespuestasAppTitle')</a></li>{{-- generated by scaffold - CuestionarioRespuesta --}}
                        <li{!! Request::is('cuestionarioDatos*') ? ' class="active"' : '' !!}><a href="/cuestionarioDatos/">@yield('cuestionarioDatosAppTitle')</a></li>{{-- generated by scaffold - CuestionarioDato --}}
                        <li{!! Request::is('combinacionClientes*') ? ' class="active"' : '' !!}><a href="/combinacionClientes/">@yield('combinacionClientesAppTitle')</a></li>{{-- generated by scaffold - CombinacionCliente --}}
                        <li{!! Request::is('combinacionClientes*') ? ' class="active"' : '' !!}><a href="/combinacionClientes/">@yield('combinacionClientesAppTitle')</a></li>{{-- generated by scaffold - CombinacionCliente --}}
                        <li{!! Request::is('combinacionClientes*') ? ' class="active"' : '' !!}><a href="/combinacionClientes/">@yield('combinacionClientesAppTitle')</a></li>{{-- generated by scaffold - CombinacionCliente --}}
                        <li{!! Request::is('diaNoHabils*') ? ' class="active"' : '' !!}><a href="/diaNoHabils/">@yield('diaNoHabilsAppTitle')</a></li>{{-- generated by scaffold - DiaNoHabil --}}
                        <li{!! Request::is('diaNoHabils*') ? ' class="active"' : '' !!}><a href="/diaNoHabils/">@yield('diaNoHabilsAppTitle')</a></li>{{-- generated by scaffold - DiaNoHabil --}}
                        <li{!! Request::is('ccuestionarios*') ? ' class="active"' : '' !!}><a href="/ccuestionarios/">@yield('ccuestionariosAppTitle')</a></li>{{-- generated by scaffold - Ccuestionario --}}
                        <li{!! Request::is('ccuestionarioPreguntas*') ? ' class="active"' : '' !!}><a href="/ccuestionarioPreguntas/">@yield('ccuestionarioPreguntasAppTitle')</a></li>{{-- generated by scaffold - CcuestionarioPreguntum --}}
                        <li{!! Request::is('ccuestionarioRespuestas*') ? ' class="active"' : '' !!}><a href="/ccuestionarioRespuestas/">@yield('ccuestionarioRespuestasAppTitle')</a></li>{{-- generated by scaffold - CcuestionarioRespuestum --}}
                        <li{!! Request::is('ccuestionarioDatos*') ? ' class="active"' : '' !!}><a href="/ccuestionarioDatos/">@yield('ccuestionarioDatosAppTitle')</a></li>{{-- generated by scaffold - CcuestionarioDato --}}
                        <li{!! Request::is('pagosLectivos*') ? ' class="active"' : '' !!}><a href="/pagosLectivos/">@yield('pagosLectivosAppTitle')</a></li>{{-- generated by scaffold - PagosLectivo --}}
                        <li{!! Request::is('cuentaContables*') ? ' class="active"' : '' !!}><a href="/cuentaContables/">@yield('cuentaContablesAppTitle')</a></li>{{-- generated by scaffold - CuentaContable --}}
                        <li{!! Request::is('reglaRecargos*') ? ' class="active"' : '' !!}><a href="/reglaRecargos/">@yield('reglaRecargosAppTitle')</a></li>{{-- generated by scaffold - ReglaRecargo --}}
                        <li{!! Request::is('pagosLectivosLns*') ? ' class="active"' : '' !!}><a href="/pagosLectivosLns/">@yield('pagosLectivosLnsAppTitle')</a></li>{{-- generated by scaffold - PagosLectivosLn --}}
                        <li{!! Request::is('planCampoFiltros*') ? ' class="active"' : '' !!}><a href="/planCampoFiltros/">@yield('planCampoFiltrosAppTitle')</a></li>{{-- generated by scaffold - PlanCampoFiltro --}}
                        <li{!! Request::is('planCondicionFiltros*') ? ' class="active"' : '' !!}><a href="/planCondicionFiltros/">@yield('planCondicionFiltrosAppTitle')</a></li>{{-- generated by scaffold - PlanCondicionFiltro --}}
                        <li{!! Request::is('tpoInformes*') ? ' class="active"' : '' !!}><a href="/tpoInformes/">@yield('tpoInformesAppTitle')</a></li>{{-- generated by scaffold - TpoInforme --}}
                        <li{!! Request::is('avisosInicios*') ? ' class="active"' : '' !!}><a href="/avisosInicios/">@yield('avisosIniciosAppTitle')</a></li>{{-- generated by scaffold - AvisosInicio --}}
                        <li{!! Request::is('smsPredefinidos*') ? ' class="active"' : '' !!}><a href="/smsPredefinidos/">@yield('smsPredefinidosAppTitle')</a></li>{{-- generated by scaffold - SmsPredefinido --}}
                        <li{!! Request::is('cajaConceptos*') ? ' class="active"' : '' !!}><a href="/cajaConceptos/">@yield('cajaConceptosAppTitle')</a></li>{{-- generated by scaffold - CajaConcepto --}}
                        <li{!! Request::is('cuentaContables*') ? ' class="active"' : '' !!}><a href="/cuentaContables/">@yield('cuentaContablesAppTitle')</a></li>{{-- generated by scaffold - CuentaContable --}}
                        <li{!! Request::is('planPagos*') ? ' class="active"' : '' !!}><a href="/planPagos/">@yield('planPagosAppTitle')</a></li>{{-- generated by scaffold - PlanPago --}}
                        <li{!! Request::is('planPagoLns*') ? ' class="active"' : '' !!}><a href="/planPagoLns/">@yield('planPagoLnsAppTitle')</a></li>{{-- generated by scaffold - PlanPagoLn --}}
                        <li{!! Request::is('formaPagos*') ? ' class="active"' : '' !!}><a href="/formaPagos/">@yield('formaPagosAppTitle')</a></li>{{-- generated by scaffold - FormaPago --}}
                        <li{!! Request::is('reglaRecargos*') ? ' class="active"' : '' !!}><a href="/reglaRecargos/">@yield('reglaRecargosAppTitle')</a></li>{{-- generated by scaffold - ReglaRecargo --}}
                        <li{!! Request::is('tipoReglas*') ? ' class="active"' : '' !!}><a href="/tipoReglas/">@yield('tipoReglasAppTitle')</a></li>{{-- generated by scaffold - TipoRegla --}}
                        <li{!! Request::is('adeudos*') ? ' class="active"' : '' !!}><a href="/adeudos/">@yield('adeudosAppTitle')</a></li>{{-- generated by scaffold - Adeudo --}}
                        <li{!! Request::is('cajas*') ? ' class="active"' : '' !!}><a href="/cajas/">@yield('cajasAppTitle')</a></li>{{-- generated by scaffold - Caja --}}
                        <li{!! Request::is('cajaLns*') ? ' class="active"' : '' !!}><a href="/cajaLns/">@yield('cajaLnsAppTitle')</a></li>{{-- generated by scaffold - CajaLn --}}
                        <li{!! Request::is('stCajas*') ? ' class="active"' : '' !!}><a href="/stCajas/">@yield('stCajasAppTitle')</a></li>{{-- generated by scaffold - StCaja --}}
                        <li{!! Request::is('segmentoMercados*') ? ' class="active"' : '' !!}><a href="/segmentoMercados/">@yield('segmentoMercadosAppTitle')</a></li>{{-- generated by scaffold - SegmentoMercado --}}
                        <li{!! Request::is('pagos*') ? ' class="active"' : '' !!}><a href="/pagos/">@yield('pagosAppTitle')</a></li>{{-- generated by scaffold - Pago --}}
                        <li{!! Request::is('pagos*') ? ' class="active"' : '' !!}><a href="/pagos/">@yield('pagosAppTitle')</a></li>{{-- generated by scaffold - Pago --}}
                        <li{!! Request::is('paises*') ? ' class="active"' : '' !!}><a href="/paises/">@yield('paisesAppTitle')</a></li>{{-- generated by scaffold - Paise --}}
                        <li{!! Request::is('historiaEventos*') ? ' class="active"' : '' !!}><a href="/historiaEventos/">@yield('historiaEventosAppTitle')</a></li>{{-- generated by scaffold - HistoriaEvento --}}
                        <li{!! Request::is('historials*') ? ' class="active"' : '' !!}><a href="/historials/">@yield('historialsAppTitle')</a></li>{{-- generated by scaffold - Historial --}}
                        <li{!! Request::is('ebanxes*') ? ' class="active"' : '' !!}><a href="/ebanxes/">@yield('ebanxesAppTitle')</a></li>{{-- generated by scaffold - Ebanx --}}
                        <li{!! Request::is('promocions*') ? ' class="active"' : '' !!}><a href="/promocions/">@yield('promocionsAppTitle')</a></li>{{-- generated by scaffold - Promocion --}}
                        <li{!! Request::is('promoPlanLns*') ? ' class="active"' : '' !!}><a href="/promoPlanLns/">@yield('promoPlanLnsAppTitle')</a></li>{{-- generated by scaffold - PromoPlanLn --}}
                        <li{!! Request::is('stEmpresas*') ? ' class="active"' : '' !!}><a href="/stEmpresas/">@yield('stEmpresasAppTitle')</a></li>{{-- generated by scaffold - StEmpresa --}}
                        <li{!! Request::is('tareasEmpresas*') ? ' class="active"' : '' !!}><a href="/tareasEmpresas/">@yield('tareasEmpresasAppTitle')</a></li>{{-- generated by scaffold - TareasEmpresa --}}
                        <li{!! Request::is('avisosEmpresas*') ? ' class="active"' : '' !!}><a href="/avisosEmpresas/">@yield('avisosEmpresasAppTitle')</a></li>{{-- generated by scaffold - AvisosEmpresa --}}
                        <li{!! Request::is('mese*') ? ' class="active"' : '' !!}><a href="/mese/">@yield('meseAppTitle')</a></li>{{-- generated by scaffold - Mese --}}
                        <li{!! Request::is('stBecas*') ? ' class="active"' : '' !!}><a href="/stBecas/">@yield('stBecasAppTitle')</a></li>{{-- generated by scaffold - StBeca --}}
                        <li{!! Request::is('autorizacionBecas*') ? ' class="active"' : '' !!}><a href="/autorizacionBecas/">@yield('autorizacionBecasAppTitle')</a></li>{{-- generated by scaffold - AutorizacionBeca --}}
                        <li{!! Request::is('autorizacionBecaComentarios*') ? ' class="active"' : '' !!}><a href="/autorizacionBecaComentarios/">@yield('autorizacionBecaComentariosAppTitle')</a></li>{{-- generated by scaffold - AutorizacionBecaComentario --}}
                        <li{!! Request::is('cursos*') ? ' class="active"' : '' !!}><a href="/cursos/">@yield('cursosAppTitle')</a></li>{{-- generated by scaffold - Curso --}}
                        <li{!! Request::is('cursosEmpresas*') ? ' class="active"' : '' !!}><a href="/cursosEmpresas/">@yield('cursosEmpresasAppTitle')</a></li>{{-- generated by scaffold - CursosEmpresa --}}
                        <li{!! Request::is('stCursoEmpresas*') ? ' class="active"' : '' !!}><a href="/stCursoEmpresas/">@yield('stCursoEmpresasAppTitle')</a></li>{{-- generated by scaffold - StCursoEmpresa --}}
                        <li{!! Request::is('cursosEmpresas*') ? ' class="active"' : '' !!}><a href="/cursosEmpresas/">@yield('cursosEmpresasAppTitle')</a></li>{{-- generated by scaffold - CursosEmpresa --}}
                        <li{!! Request::is('cotizacionCursos*') ? ' class="active"' : '' !!}><a href="/cotizacionCursos/">@yield('cotizacionCursosAppTitle')</a></li>{{-- generated by scaffold - CotizacionCurso --}}
                        <li{!! Request::is('tipoPrecioCotis*') ? ' class="active"' : '' !!}><a href="/tipoPrecioCotis/">@yield('tipoPrecioCotisAppTitle')</a></li>{{-- generated by scaffold - TipoPrecioCoti --}}
                        <li{!! Request::is('cotizacionLns*') ? ' class="active"' : '' !!}><a href="/cotizacionLns/">@yield('cotizacionLnsAppTitle')</a></li>{{-- generated by scaffold - CotizacionLn --}}
                        <li{!! Request::is('facturaCotizacions*') ? ' class="active"' : '' !!}><a href="/facturaCotizacions/">@yield('facturaCotizacionsAppTitle')</a></li>{{-- generated by scaffold - FacturaCotizacion --}}
                        <li{!! Request::is('stInscripcions*') ? ' class="active"' : '' !!}><a href="/stInscripcions/">@yield('stInscripcionsAppTitle')</a></li>{{-- generated by scaffold - StInscripcion --}}
                        <li{!! Request::is('consultaCalificacions*') ? ' class="active"' : '' !!}><a href="/consultaCalificacions/">@yield('consultaCalificacionsAppTitle')</a></li>{{-- generated by scaffold - ConsultaCalificacion --}}
                        <li{!! Request::is('eventoClientes*') ? ' class="active"' : '' !!}><a href="/eventoClientes/">@yield('eventoClientesAppTitle')</a></li>{{-- generated by scaffold - EventoCliente --}}
                        <li{!! Request::is('historiaClientes*') ? ' class="active"' : '' !!}><a href="/historiaClientes/">@yield('historiaClientesAppTitle')</a></li>{{-- generated by scaffold - HistoriaCliente --}}
                        <li{!! Request::is('cuentasEfectivos*') ? ' class="active"' : '' !!}><a href="/cuentasEfectivos/">@yield('cuentasEfectivosAppTitle')</a></li>{{-- generated by scaffold - CuentasEfectivo --}}
                        <li{!! Request::is('egresosConceptos*') ? ' class="active"' : '' !!}><a href="/egresosConceptos/">@yield('egresosConceptosAppTitle')</a></li>{{-- generated by scaffold - EgresosConcepto --}}
                        <li{!! Request::is('asuntos*') ? ' class="active"' : '' !!}><a href="/asuntos/">@yield('asuntosAppTitle')</a></li>{{-- generated by scaffold - Asunto --}}
                        <li{!! Request::is('egresos*') ? ' class="active"' : '' !!}><a href="/egresos/">@yield('egresosAppTitle')</a></li>{{-- generated by scaffold - Egreso --}}
                        <li{!! Request::is('cuentasEfectivoPlantels*') ? ' class="active"' : '' !!}><a href="/cuentasEfectivoPlantels/">@yield('cuentasEfectivoPlantelsAppTitle')</a></li>{{-- generated by scaffold - CuentasEfectivoPlantel --}}
                        <li{!! Request::is('hCuentasEfectivos*') ? ' class="active"' : '' !!}><a href="/hCuentasEfectivos/">@yield('hCuentasEfectivosAppTitle')</a></li>{{-- generated by scaffold - HCuentasEfectivo --}}
                        <li{!! Request::is('ingresoEgresos*') ? ' class="active"' : '' !!}><a href="/ingresoEgresos/">@yield('ingresoEgresosAppTitle')</a></li>{{-- generated by scaffold - IngresoEgreso --}}
                        <li{!! Request::is('transferences*') ? ' class="active"' : '' !!}><a href="/transferences/">@yield('transferencesAppTitle')</a></li>{{-- generated by scaffold - Transference --}}
                        <li{!! Request::is('transferences*') ? ' class="active"' : '' !!}><a href="/transferences/">@yield('transferencesAppTitle')</a></li>{{-- generated by scaffold - Transference --}}
                        <li{!! Request::is('hEstatuses*') ? ' class="active"' : '' !!}><a href="/hEstatuses/">@yield('hEstatusesAppTitle')</a></li>{{-- generated by scaffold - HEstatus --}}
                        <li{!! Request::is('docPlantels*') ? ' class="active"' : '' !!}><a href="/docPlantels/">@yield('docPlantelsAppTitle')</a></li>{{-- generated by scaffold - DocPlantel --}}
                        <li{!! Request::is('docPlantelPlantels*') ? ' class="active"' : '' !!}><a href="/docPlantelPlantels/">@yield('docPlantelPlantelsAppTitle')</a></li>{{-- generated by scaffold - DocPlantelPlantel --}}
                        <li{!! Request::is('vinculacions*') ? ' class="active"' : '' !!}><a href="/vinculacions/">@yield('vinculacionsAppTitle')</a></li>{{-- generated by scaffold - Vinculacion --}}
                        <li{!! Request::is('vinculacions*') ? ' class="active"' : '' !!}><a href="/vinculacions/">@yield('vinculacionsAppTitle')</a></li>{{-- generated by scaffold - Vinculacion --}}
                        <li{!! Request::is('vinculacionHoras*') ? ' class="active"' : '' !!}><a href="/vinculacionHoras/">@yield('vinculacionHorasAppTitle')</a></li>{{-- generated by scaffold - VinculacionHora --}}
                        <li{!! Request::is('docVinculacions*') ? ' class="active"' : '' !!}><a href="/docVinculacions/">@yield('docVinculacionsAppTitle')</a></li>{{-- generated by scaffold - DocVinculacion --}}
                        <li{!! Request::is('docVinculacionVinculacions*') ? ' class="active"' : '' !!}><a href="/docVinculacionVinculacions/">@yield('docVinculacionVinculacionsAppTitle')</a></li>{{-- generated by scaffold - DocVinculacionVinculacion --}}
                        <li{!! Request::is('escolaridads*') ? ' class="active"' : '' !!}><a href="/escolaridads/">@yield('escolaridadsAppTitle')</a></li>{{-- generated by scaffold - Escolaridad --}}
                        <li{!! Request::is('unidadUsos*') ? ' class="active"' : '' !!}><a href="/unidadUsos/">@yield('unidadUsosAppTitle')</a></li>{{-- generated by scaffold - UnidadUso --}}
                        <li{!! Request::is('categoriaArticulos*') ? ' class="active"' : '' !!}><a href="/categoriaArticulos/">@yield('categoriaArticulosAppTitle')</a></li>{{-- generated by scaffold - CategoriaArticulo --}}
                        <li{!! Request::is('articulos*') ? ' class="active"' : '' !!}><a href="/articulos/">@yield('articulosAppTitle')</a></li>{{-- generated by scaffold - Articulo --}}
                        <li{!! Request::is('entradaSalidas*') ? ' class="active"' : '' !!}><a href="/entradaSalidas/">@yield('entradaSalidasAppTitle')</a></li>{{-- generated by scaffold - EntradaSalida --}}
                        <li{!! Request::is('existencias*') ? ' class="active"' : '' !!}><a href="/existencias/">@yield('existenciasAppTitle')</a></li>{{-- generated by scaffold - Existencium --}}
                        <li{!! Request::is('movimientos*') ? ' class="active"' : '' !!}><a href="/movimientos/">@yield('movimientosAppTitle')</a></li>{{-- generated by scaffold - Movimiento --}}
                        <li{!! Request::is('plantillaEmpresas*') ? ' class="active"' : '' !!}><a href="/plantillaEmpresas/">@yield('plantillaEmpresasAppTitle')</a></li>{{-- generated by scaffold - PlantillaEmpresa --}}
                        <li{!! Request::is('plantillaEmpresaCampos*') ? ' class="active"' : '' !!}><a href="/plantillaEmpresaCampos/">@yield('plantillaEmpresaCamposAppTitle')</a></li>{{-- generated by scaffold - PlantillaEmpresaCampo --}}
                        <li{!! Request::is('plantillaEmpresaConds*') ? ' class="active"' : '' !!}><a href="/plantillaEmpresaConds/">@yield('plantillaEmpresaCondsAppTitle')</a></li>{{-- generated by scaffold - PlantillaEmpresaCond --}}
                        <li{!! Request::is('ubicacionArts*') ? ' class="active"' : '' !!}><a href="/ubicacionArts/">@yield('ubicacionArtsAppTitle')</a></li>{{-- generated by scaffold - UbicacionArt --}}
                        <li{!! Request::is('tpoArticulos*') ? ' class="active"' : '' !!}><a href="/tpoArticulos/">@yield('tpoArticulosAppTitle')</a></li>{{-- generated by scaffold - TpoArticulo --}}
                        



                        </ul>
                    </li>

                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>