<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
    echo'<pre>';
    var_dump($query->sql);
    var_dump($query->bindings);
    var_dump($query->time);
    echo'</pre>';
});
*/
Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('home', array(
        'as' => 'home',
        'uses' => 'HomeController@index')
);

Route::resource("apples","ApplesController");// generated by scaffold - Apple
Route::get("apples/apple/{apples}/duplicate", ['as' => 'apples.duplicate', 'uses' => 'ApplesController@duplicate']);// generated by scaffold - Apple
Route::resource("menus","MenusController");// generated by scaffold - Menu
Route::get("menus/menu/{menus}/duplicate", ['as' => 'menus.duplicate', 'uses' => 'MenusController@duplicate']);// generated by scaffold - Menu

Route::resource("banderas","BanderasController");// generated by scaffold - Bandera
Route::get("banderas/bandera/{banderas}/duplicate", ['as' => 'banderas.duplicate', 'uses' => 'BanderasController@duplicate']);// generated by scaffold - Bandera

//Route::resource("lectivos","LectivosController");// generated by scaffold - Lectivo
//Route::get("lectivos/lectivo/{lectivos}/duplicate", ['as' => 'lectivos.duplicate', 'uses' => 'LectivosController@duplicate']);// generated by scaffold - Lectivo
    Route::get('lectivos/index', array(
        'as' => 'lectivos.index',
        'middleware' => 'permission:lectivos.index',
        'uses' => 'LectivosController@index')
    )->middleware('auth');

    Route::get('/lectivos/create', array(
        'as' => 'lectivos.create',
        'middleware' => 'permission:lectivos.create',
        'uses' => 'LectivosController@create')
    )->middleware('auth');
    Route::post('lectivos/store', array(
        'as' => 'lectivos.store',
        'middleware' => 'permission:lectivos.store',
        'uses' => 'LectivosController@store')
    )->middleware('auth');
    Route::get('/lectivos/show/{id}', array(
        'as' => 'lectivos.show',
        'middleware' => 'permission:lectivos.show',
        'uses' => 'LectivosController@show')
    )->middleware('auth');
    Route::get('/lectivos/edit/{id}', array(
        'as' => 'lectivos.edit',
        'middleware' => 'permission:lectivos.edit',
        'uses' => 'LectivosController@edit')
    )->middleware('auth');
    Route::post('/lectivos/update/{id}', array(
        'as' => 'lectivos.update',
        'middleware' => 'permission:lectivos.update',
        'uses' => 'LectivosController@update')
    )->middleware('auth');
    Route::delete('/lectivos/destroy/{id}', array(
        'as' => 'lectivos.destroy',
        'middleware' => 'permission:lectivos.destroy',
        'uses' => 'LectivosController@destroy')
    )->middleware('auth');
    Route::get('/lectivos/duplicate/{id}', array(
        'as' => 'lectivos.duplicate',
        'middleware' => 'permission:lectivos.duplicate',
        'uses' => 'LectivosController@duplicate')
    )->middleware('auth');
//Route::resource("plantels","PlantelsController");// generated by scaffold - Plantel
//Route::get("plantels/plantel/{plantels}/duplicate", ['as' => 'plantels.duplicate', 'uses' => 'PlantelsController@duplicate']);// generated by scaffold - Plantel
    Route::get('plantels/index', array(
        'as' => 'plantels.index',
        'middleware' => 'permission:plantels.index',
        'uses' => 'PlantelsController@index')
    )->middleware('auth');

    Route::get('/plantels/create', array(
        'as' => 'plantels.create',
        'middleware' => 'permission:plantels.create',
        'uses' => 'PlantelsController@create')
    )->middleware('auth');
    Route::post('plantels/store', array(
        'as' => 'plantels.store',
        'middleware' => 'permission:plantels.store',
        'uses' => 'PlantelsController@store')
    )->middleware('auth');
    Route::get('/plantels/show/{id}', array(
        'as' => 'plantels.show',
        'middleware' => 'permission:plantels.show',
        'uses' => 'PlantelsController@show')
    )->middleware('auth');
    Route::get('/plantels/edit/{id}', array(
        'as' => 'plantels.edit',
        'middleware' => 'permission:plantels.edit',
        'uses' => 'PlantelsController@edit')
    )->middleware('auth');
    Route::post('/plantels/update/{id}', array(
        'as' => 'plantels.update',
        'middleware' => 'permission:plantels.update',
        'uses' => 'PlantelsController@update')
    )->middleware('auth');
    Route::delete('/plantels/destroy/{id}', array(
        'as' => 'plantels.destroy',
        'middleware' => 'permission:plantels.destroy',
        'uses' => 'PlantelsController@destroy')
    )->middleware('auth');
    Route::get('/plantels/duplicate/{id}', array(
        'as' => 'plantels.duplicate',
        'middleware' => 'permission:plantels.duplicate',
        'uses' => 'PlantelsController@duplicate')
    )->middleware('auth');
//Route::resource("areas","AreasController");// generated by scaffold - Area
//Route::get("areas/area/{areas}/duplicate", ['as' => 'areas.duplicate', 'uses' => 'AreasController@duplicate']);// generated by scaffold - Area
    Route::get('areas/index', array(
        'as' => 'areas.index',
        'middleware' => 'permission:areas.index',
        'uses' => 'AreasController@index')
    )->middleware('auth');

    Route::get('/areas/create', array(
        'as' => 'areas.create',
        'middleware' => 'permission:areas.create',
        'uses' => 'AreasController@create')
    )->middleware('auth');
    Route::post('areas/store', array(
        'as' => 'areas.store',
        'middleware' => 'permission:areas.store',
        'uses' => 'AreasController@store')
    )->middleware('auth');
    Route::get('/areas/show/{id}', array(
        'as' => 'areas.show',
        'middleware' => 'permission:areas.show',
        'uses' => 'AreasController@show')
    )->middleware('auth');
    Route::get('/areas/edit/{id}', array(
        'as' => 'areas.edit',
        'middleware' => 'permission:areas.edit',
        'uses' => 'AreasController@edit')
    )->middleware('auth');
    Route::post('/areas/update/{id}', array(
        'as' => 'areas.update',
        'middleware' => 'permission:areas.update',
        'uses' => 'AreasController@update')
    )->middleware('auth');
    Route::delete('/areas/destroy/{id}', array(
        'as' => 'areas.destroy',
        'middleware' => 'permission:areas.destroy',
        'uses' => 'AreasController@destroy')
    )->middleware('auth');
    Route::get('/areas/duplicate/{id}', array(
        'as' => 'areas.duplicate',
        'middleware' => 'permission:areas.duplicate',
        'uses' => 'AreasController@duplicate')
    )->middleware('auth');
//Route::resource("puestos","PuestosController");// generated by scaffold - Puesto
//Route::get("puestos/puesto/{puestos}/duplicate", ['as' => 'puestos.duplicate', 'uses' => 'PuestosController@duplicate']);// generated by scaffold - Puesto
    Route::get('puestos/index', array(
        'as' => 'puestos.index',
        'middleware' => 'permission:puestos.index',
        'uses' => 'PuestosController@index')
    )->middleware('auth');

    Route::get('/puestos/create', array(
        'as' => 'puestos.create',
        'middleware' => 'permission:puestos.create',
        'uses' => 'PuestosController@create')
    )->middleware('auth');
    Route::post('puestos/store', array(
        'as' => 'puestos.store',
        'middleware' => 'permission:puestos.store',
        'uses' => 'PuestosController@store')
    )->middleware('auth');
    Route::get('/puestos/show/{id}', array(
        'as' => 'puestos.show',
        'middleware' => 'permission:puestos.show',
        'uses' => 'PuestosController@show')
    )->middleware('auth');
    Route::get('/puestos/edit/{id}', array(
        'as' => 'puestos.edit',
        'middleware' => 'permission:puestos.edit',
        'uses' => 'PuestosController@edit')
    )->middleware('auth');
    Route::post('/puestos/update/{id}', array(
        'as' => 'puestos.update',
        'middleware' => 'permission:puestos.update',
        'uses' => 'PuestosController@update')
    )->middleware('auth');
    Route::delete('/puestos/destroy/{id}', array(
        'as' => 'puestos.destroy',
        'middleware' => 'permission:puestos.destroy',
        'uses' => 'PuestosController@destroy')
    )->middleware('auth');
    Route::get('/puestos/duplicate/{id}', array(
        'as' => 'puestos.duplicate',
        'middleware' => 'permission:puestos.duplicate',
        'uses' => 'PuestosController@duplicate')
    )->middleware('auth');    
//Route::resource("stEmpleados","StEmpleadosController");// generated by scaffold - StEmpleado
//Route::get("stEmpleados/stEmpleado/{stEmpleados}/duplicate", ['as' => 'stEmpleados.duplicate', 'uses' => 'StEmpleadosController@duplicate']);// generated by scaffold - StEmpleado
    Route::get('stEmpleados/index', array(
        'as' => 'stEmpleados.index',
        'middleware' => 'permission:stEmpleados.index',
        'uses' => 'StEmpleadosController@index')
    )->middleware('auth');

    Route::get('/stEmpleados/create', array(
        'as' => 'stEmpleados.create',
        'middleware' => 'permission:stEmpleados.create',
        'uses' => 'StEmpleadosController@create')
    )->middleware('auth');
    Route::post('stEmpleados/store', array(
        'as' => 'stEmpleados.store',
        'middleware' => 'permission:stEmpleados.store',
        'uses' => 'StEmpleadosController@store')
    )->middleware('auth');
    Route::get('/stEmpleados/show/{id}', array(
        'as' => 'stEmpleados.show',
        'middleware' => 'permission:stEmpleados.show',
        'uses' => 'StEmpleadosController@show')
    )->middleware('auth');
    Route::get('/stEmpleados/edit/{id}', array(
        'as' => 'stEmpleados.edit',
        'middleware' => 'permission:stEmpleados.edit',
        'uses' => 'StEmpleadosController@edit')
    )->middleware('auth');
    Route::post('/stEmpleados/update/{id}', array(
        'as' => 'stEmpleados.update',
        'middleware' => 'permission:stEmpleados.update',
        'uses' => 'StEmpleadosController@update')
    )->middleware('auth');
    Route::delete('/stEmpleados/destroy/{id}', array(
        'as' => 'stEmpleados.destroy',
        'middleware' => 'permission:stEmpleados.destroy',
        'uses' => 'StEmpleadosController@destroy')
    )->middleware('auth');
    Route::get('/stEmpleados/duplicate/{id}', array(
        'as' => 'stEmpleados.duplicate',
        'middleware' => 'permission:stEmpleados.duplicate',
        'uses' => 'StEmpleadosController@duplicate')
    )->middleware('auth');
//Route::resource("empleados","EmpleadosController");// generated by scaffold - Empleado
//Route::get("empleados/empleado/{empleados}/duplicate", ['as' => 'empleados.duplicate', 'uses' => 'EmpleadosController@duplicate']);// generated by scaffold - Empleado
    Route::get('empleados/index', array(
        'as' => 'empleados.index',
        'middleware' => 'permission:empleados.index',
        'uses' => 'EmpleadosController@index')
    )->middleware('auth');

    Route::get('/empleados/create', array(
        'as' => 'empleados.create',
        'middleware' => 'permission:empleados.create',
        'uses' => 'EmpleadosController@create')
    )->middleware('auth');
    Route::post('empleados/store', array(
        'as' => 'empleados.store',
        'middleware' => 'permission:empleados.store',
        'uses' => 'EmpleadosController@store')
    )->middleware('auth');
    Route::get('/empleados/show/{id}', array(
        'as' => 'empleados.show',
        'middleware' => 'permission:empleados.show',
        'uses' => 'EmpleadosController@show')
    )->middleware('auth');
    Route::get('/empleados/edit/{id}', array(
        'as' => 'empleados.edit',
        'middleware' => 'permission:empleados.edit',
        'uses' => 'EmpleadosController@edit')
    )->middleware('auth');
    Route::post('/empleados/update/{id}', array(
        'as' => 'empleados.update',
        'middleware' => 'permission:empleados.update',
        'uses' => 'EmpleadosController@update')
    )->middleware('auth');
    Route::delete('/empleados/destroy/{id}', array(
        'as' => 'empleados.destroy',
        'middleware' => 'permission:empleados.destroy',
        'uses' => 'EmpleadosController@destroy')
    )->middleware('auth');
    Route::get('/empleados/duplicate/{id}', array(
        'as' => 'empleados.duplicate',
        'middleware' => 'permission:empleados.duplicate',
        'uses' => 'EmpleadosController@duplicate')
    )->middleware('auth');
    Route::get('/empleados/usuarios', array(
        'as' => 'empleados.usuarios',
        //'middleware' => 'permission:clientes.edit',
        'uses' => 'EmpleadosController@usuarios')
    )->middleware('auth');
    Route::get('/getPlantel', array(
        'as' => 'empleados.getPlantel',
        //'middleware' => 'permission:tareas.show',
        'uses' => 'EmpleadosController@getPlantel')
    )->middleware('auth');
///////////////////////////////////////////////////////////////////////////////////////////
    Route::get('zip/imagenes', function () {
            $files = glob(public_path('imagenes'));
            if(file_exists(public_path().'\\archivos_imagenes.zip')){
                unlink(public_path().'\\archivos_imagenes.zip');
            }
            Zipper::make(public_path().'\\archivos_imagenes.zip')->add($files);
            while(!file_exists(public_path().'\\archivos_imagenes.zip')){
                sleep(3);
            }
            return response()->download(public_path().'\\archivos_imagenes.zip');
    })->name('zip.imagenes');
///////////////////////////////////////////////////////////////////////////////////////////
    Route::get('/down', function () {
        Artisan::call('down');        
    })->name('down');
    Route::get('/EnviarCorreos', function () {
        Artisan::call('ian:EnviarCorreos');        
        dd("Correos Enviados");
    })->name('ec');

    //->middleware('permission:empleados.duplicate');
//Route::resource("stClientes","StClientesController");// generated by scaffold - StCliente
//Route::get("stClientes/stCliente/{stClientes}/duplicate", ['as' => 'stClientes.duplicate', 'uses' => 'StClientesController@duplicate']);// generated by scaffold - StCliente
    Route::get('stClientes/index', array(
        'as' => 'stClientes.index',
        'middleware' => 'permission:stClientes.index',
        'uses' => 'StClientesController@index')
    )->middleware('auth');

    Route::get('/stClientes/create', array(
        'as' => 'stClientes.create',
        'middleware' => 'permission:stClientes.create',
        'uses' => 'StClientesController@create')
    )->middleware('auth');
    Route::post('stClientes/store', array(
        'as' => 'stClientes.store',
        'middleware' => 'permission:stClientes.store',
        'uses' => 'StClientesController@store')
    )->middleware('auth');
    Route::get('/stClientes/show/{id}', array(
        'as' => 'stClientes.show',
        'middleware' => 'permission:stClientes.show',
        'uses' => 'StClientesController@show')
    )->middleware('auth');
    Route::get('/stClientes/edit/{id}', array(
        'as' => 'stClientes.edit',
        'middleware' => 'permission:stClientes.edit',
        'uses' => 'StClientesController@edit')
    )->middleware('auth');
    Route::post('/stClientes/update/{id}', array(
        'as' => 'stClientes.update',
        'middleware' => 'permission:stClientes.update',
        'uses' => 'StClientesController@update')
    )->middleware('auth');
    Route::delete('/stClientes/destroy/{id}', array(
        'as' => 'stClientes.destroy',
        'middleware' => 'permission:stClientes.destroy',
        'uses' => 'StClientesController@destroy')
    )->middleware('auth');
    Route::get('/stClientes/duplicate/{id}', array(
        'as' => 'stClientes.duplicate',
        'middleware' => 'permission:stClientes.duplicate',
        'uses' => 'StClientesController@duplicate')
    )->middleware('auth');
//Route::resource("ofertas","OfertasController");// generated by scaffold - Ofertum
//Route::get("ofertas/ofertum/{ofertas}/duplicate", ['as' => 'ofertas.duplicate', 'uses' => 'OfertasController@duplicate']);// generated by scaffold - Ofertum
Route::get('ofertas/index', array(
        'as' => 'ofertas.index',
        'middleware' => 'permission:ofertas.index',
        'uses' => 'OfertasController@index')
    )->middleware('auth');

    Route::get('/ofertas/create', array(
        'as' => 'ofertas.create',
        'middleware' => 'permission:ofertas.create',
        'uses' => 'OfertasController@create')
    )->middleware('auth');
    Route::post('ofertas/store', array(
        'as' => 'ofertas.store',
        'middleware' => 'permission:ofertas.store',
        'uses' => 'OfertasController@store')
    )->middleware('auth');
    Route::get('/ofertas/show/{id}', array(
        'as' => 'ofertas.show',
        'middleware' => 'permission:ofertas.show',
        'uses' => 'OfertasController@show')
    )->middleware('auth');
    Route::get('/ofertas/edit/{id}', array(
        'as' => 'ofertas.edit',
        'middleware' => 'permission:ofertas.edit',
        'uses' => 'OfertasController@edit')
    )->middleware('auth');
    Route::post('/ofertas/update/{id}', array(
        'as' => 'ofertas.update',
        'middleware' => 'permission:ofertas.update',
        'uses' => 'OfertasController@update')
    )->middleware('auth');
    Route::delete('/ofertas/destroy/{id}', array(
        'as' => 'ofertas.destroy',
        'middleware' => 'permission:ofertas.destroy',
        'uses' => 'OfertasController@destroy')
    )->middleware('auth');
    Route::get('/ofertas/duplicate/{id}', array(
        'as' => 'ofertas.duplicate',
        'middleware' => 'permission:ofertas.duplicate',
        'uses' => 'OfertasController@duplicate')
    )->middleware('auth');
//Route::resource("medios","MediosController");// generated by scaffold - Medio
//Route::get("medios/medio/{medios}/duplicate", ['as' => 'medios.duplicate', 'uses' => 'MediosController@duplicate']);// generated by scaffold - Medio
Route::get('medios/index', array(
        'as' => 'medios.index',
        'middleware' => 'permission:medios.index',
        'uses' => 'MediosController@index')
    )->middleware('auth');

    Route::get('/medios/create', array(
        'as' => 'medios.create',
        'middleware' => 'permission:medios.create',
        'uses' => 'MediosController@create')
    )->middleware('auth');
    Route::post('medios/store', array(
        'as' => 'medios.store',
        'middleware' => 'permission:medios.store',
        'uses' => 'MediosController@store')
    )->middleware('auth');
    Route::get('/medios/show/{id}', array(
        'as' => 'medios.show',
        'middleware' => 'permission:medios.show',
        'uses' => 'MediosController@show')
    )->middleware('auth');
    Route::get('/medios/edit/{id}', array(
        'as' => 'medios.edit',
        'middleware' => 'permission:medios.edit',
        'uses' => 'MediosController@edit')
    )->middleware('auth');
    Route::post('/medios/update/{id}', array(
        'as' => 'medios.update',
        'middleware' => 'permission:medios.update',
        'uses' => 'MediosController@update')
    )->middleware('auth');
    Route::delete('/medios/destroy/{id}', array(
        'as' => 'medios.destroy',
        'middleware' => 'permission:medios.destroy',
        'uses' => 'MediosController@destroy')
    )->middleware('auth');
    Route::get('/medios/duplicate/{id}', array(
        'as' => 'medios.duplicate',
        'middleware' => 'permission:medios.duplicate',
        'uses' => 'MediosController@duplicate')
    )->middleware('auth');
//Route::resource("tareas","TareasController");// generated by scaffold - Tarea
//Route::get("tareas/tarea/{tareas}/duplicate", ['as' => 'tareas.duplicate', 'uses' => 'TareasController@duplicate']);// generated by scaffold - Tarea
    Route::get('tareas/index', array(
        'as' => 'tareas.index',
        'middleware' => 'permission:tareas.index',
        'uses' => 'TareasController@index')
    )->middleware('auth');

    Route::get('/tareas/create', array(
        'as' => 'tareas.create',
        'middleware' => 'permission:tareas.create',
        'uses' => 'TareasController@create')
    )->middleware('auth');
    Route::post('tareas/store', array(
        'as' => 'tareas.store',
        'middleware' => 'permission:tareas.store',
        'uses' => 'TareasController@store')
    )->middleware('auth');
    Route::get('/tareas/show/{id}', array(
        'as' => 'tareas.show',
        'middleware' => 'permission:tareas.show',
        'uses' => 'TareasController@show')
    )->middleware('auth');
    Route::get('/tareas/edit/{id}', array(
        'as' => 'tareas.edit',
        'middleware' => 'permission:tareas.edit',
        'uses' => 'TareasController@edit')
    )->middleware('auth');
    Route::post('/tareas/update/{id}', array(
        'as' => 'tareas.update',
        'middleware' => 'permission:tareas.update',
        'uses' => 'TareasController@update')
    )->middleware('auth');
    Route::delete('/tareas/destroy/{id}', array(
        'as' => 'tareas.destroy',
        'middleware' => 'permission:tareas.destroy',
        'uses' => 'TareasController@destroy')
    )->middleware('auth');
    Route::get('/tareas/duplicate/{id}', array(
        'as' => 'tareas.duplicate',
        'middleware' => 'permission:tareas.duplicate',
        'uses' => 'TareasController@duplicate')
    )->middleware('auth');    
//Route::resource("estados","EstadosController");// generated by scaffold - Estado
//Route::get("estados/estado/{estados}/duplicate", ['as' => 'estados.duplicate', 'uses' => 'EstadosController@duplicate']);// generated by scaffold - Estado
//Route::resource("municipios","MunicipiosController");// generated by scaffold - Municipio
//Route::get("municipios/municipio/{municipios}/duplicate", ['as' => 'municipios.duplicate', 'uses' => 'MunicipiosController@duplicate']);// generated by scaffold - Municipio
    Route::get('/getCmbMunicipios', array(
        'as' => 'municipios.getCmbMunicipios',
        //'middleware' => 'permission:tareas.show',
        'uses' => 'EstadosController@getCmbMunicipios')
    )->middleware('auth');
//Route::resource("clientes","ClientesController");// generated by scaffold - Cliente
//Route::get("clientes/cliente/{clientes}/duplicate", ['as' => 'clientes.duplicate', 'uses' => 'ClientesController@duplicate']);// generated by scaffold - Cliente
    Route::get('clientes/index', array(
        'as' => 'clientes.index',
        'middleware' => 'permission:clientes.index',
        'uses' => 'ClientesController@index')
    )->middleware('auth');
    Route::get('clientes/indexList', array(
        'as' => 'clientes.indexList',
        //'middleware' => 'permission:clientes.indexList',
        'uses' => 'ClientesController@indexLista')
    )->middleware('auth');
    Route::get('clientes/list', array(
        'as' => 'clientes.list',
        //'middleware' => 'permission:clientes.indexList',
        'uses' => 'ClientesController@lista')
    )->middleware('auth');
    Route::get('/clientes/create', array(
        'as' => 'clientes.create',
        'middleware' => 'permission:clientes.create',
        'uses' => 'ClientesController@create')
    )->middleware('auth');
    Route::post('clientes/store', array(
        'as' => 'clientes.store',
        'middleware' => 'permission:clientes.store',
        'uses' => 'ClientesController@store')
    )->middleware('auth');
    Route::get('/clientes/show/{id}', array(
        'as' => 'clientes.show',
        'middleware' => 'permission:clientes.show',
        'uses' => 'ClientesController@show')
    )->middleware('auth');
    Route::get('/clientes/edit/{id}', array(
        'as' => 'clientes.edit',
        'middleware' => 'permission:clientes.edit',
        'uses' => 'ClientesController@edit')
    )->middleware('auth');
    Route::post('/clientes/update/{id}', array(
        'as' => 'clientes.update',
        'middleware' => 'permission:clientes.update',
        'uses' => 'ClientesController@update')
    )->middleware('auth');
    Route::get('/clientes/confirmaCorreo/{id}', array(
        'as' => 'clientes.confirmaCorreo',
        //'middleware' => 'permission:empleados.confirmaCorreo',
        'uses' => 'ClientesController@confirmaCorreo')
    )->middleware('auth');
    Route::delete('/clientes/destroy/{id}', array(
        'as' => 'clientes.destroy',
        'middleware' => 'permission:clientes.destroy',
        'uses' => 'ClientesController@destroy')
    )->middleware('auth');
    Route::get('/clientes/duplicate/{id}', array(
        'as' => 'clientes.duplicate',
        'middleware' => 'permission:clientes.duplicate',
        'uses' => 'ClientesController@duplicate')
    )->middleware('auth');
    // app/routes.php
    Route::get('/clientes/autocomplete', array(
        'as' => 'clientes.autocomplete',
        //'middleware' => 'permission:clientes.edit',
        'uses' => 'ClientesController@autocomplete')
    )->middleware('auth');
    Route::get('/clientes/carga', array(
        'as' => 'clientes.carga',
        //'middleware' => 'permission:clientes.edit',
        'uses' => 'ClientesController@carga')
    )->middleware('auth');
    Route::post('/clientes/carga', array(
        'as' => 'clientes.carga',
        'middleware' => 'permission:clientes.carga',
        'uses' => 'ClientesController@cargaFile')
    )->middleware('auth');
    Route::post('/clientes/enviaSms', array(
        'as' => 'clientes.enviaSms',
        'middleware' => 'permission:clientes.enviaSms',
        'uses' => 'ClientesController@enviaSms')
    )->middleware('auth');
    Route::post('/clientes/enviaMail', array(
        'as' => 'clientes.enviaMail',
        'middleware' => 'permission:clientes.enviaMail',
        'uses' => 'ClientesController@enviaMail')
    )->middleware('auth');
    Route::get('/clientes/cmbMClientes', array(
        'as' => 'clientes.cmbMClientes',
        //'middleware' => 'permission:clientes.cmbMClientes',
        'uses' => 'ClientesController@cmbMClientes')
    )->middleware('auth');

//    Route::resource("preguntas","PreguntasController");// generated by scaffold - Preguntum
//Route::get("preguntas/preguntum/{preguntas}/duplicate", ['as' => 'preguntas.duplicate', 'uses' => 'PreguntasController@duplicate']);// generated by scaffold - Preguntum
    Route::get('preguntas/index', array(
        'as' => 'preguntas.index',
        'middleware' => 'permission:preguntas.index',
        'uses' => 'PreguntasController@index')
    )->middleware('auth');

    Route::get('/preguntas/create', array(
        'as' => 'preguntas.create',
        'middleware' => 'permission:preguntas.create',
        'uses' => 'PreguntasController@create')
    )->middleware('auth');
    Route::post('preguntas/store', array(
        'as' => 'preguntas.store',
        'middleware' => 'permission:preguntas.store',
        'uses' => 'PreguntasController@store')
    )->middleware('auth');
    Route::get('/preguntas/show/{id}', array(
        'as' => 'preguntas.show',
        'middleware' => 'permission:preguntas.show',
        'uses' => 'PreguntasController@show')
    )->middleware('auth');
    Route::get('/preguntas/edit/{id}', array(
        'as' => 'preguntas.edit',
        'middleware' => 'permission:preguntas.edit',
        'uses' => 'PreguntasController@edit')
    )->middleware('auth');
    Route::post('/preguntas/update/{id}', array(
        'as' => 'preguntas.update',
        'middleware' => 'permission:preguntas.update',
        'uses' => 'PreguntasController@update')
    )->middleware('auth');
    Route::delete('/preguntas/destroy/{id}', array(
        'as' => 'preguntas.destroy',
        'middleware' => 'permission:preguntas.destroy',
        'uses' => 'PreguntasController@destroy')
    )->middleware('auth');
    Route::get('/preguntas/duplicate/{id}', array(
        'as' => 'preguntas.duplicate',
        'middleware' => 'permission:preguntas.duplicate',
        'uses' => 'PreguntasController@duplicate')
    )->middleware('auth');
    // app/routes.php

//Route::resource("preguntaClientes","PreguntaClientesController");// generated by scaffold - PreguntaCliente
//Route::get("preguntaClientes/preguntaCliente/{preguntaClientes}/duplicate", ['as' => 'preguntaClientes.duplicate', 'uses' => 'PreguntaClientesController@duplicate']);// generated by scaffold - PreguntaCliente
    Route::get('/preguntasClientes/destroy/{id}', array(
        'as' => 'preguntasClientes.destroy',
        //'middleware' => 'permission:preguntas.destroy',
        'uses' => 'PreguntaClientesController@destroy')
    )->middleware('auth');

//Route::resource("periodos","PeriodosController");// generated by scaffold - Periodo
//Route::get("periodos/periodo/{periodos}/duplicate", ['as' => 'periodos.duplicate', 'uses' => 'PeriodosController@duplicate']);// generated by scaffold - Periodo
//Route::resource("plantillas","PlantillasController");// generated by scaffold - Plantilla
//Route::get("plantillas/plantilla/{plantillas}/duplicate", ['as' => 'plantillas.duplicate', 'uses' => 'PlantillasController@duplicate']);// generated by scaffold - Plantilla
    Route::get('plantillas/index', array(
        'as' => 'plantillas.index',
        'middleware' => 'permission:plantillas.index',
        'uses' => 'PlantillasController@index')
    )->middleware('auth');

    Route::get('/plantillas/create', array(
        'as' => 'plantillas.create',
        'middleware' => 'permission:plantillas.create',
        'uses' => 'PlantillasController@create')
    )->middleware('auth');
    Route::post('plantillas/store', array(
        'as' => 'plantillas.store',
        'middleware' => 'permission:plantillas.store',
        'uses' => 'PlantillasController@store')
    )->middleware('auth');
    Route::get('/plantillas/show/{id}', array(
        'as' => 'plantillas.show',
        'middleware' => 'permission:plantillas.show',
        'uses' => 'PlantillasController@show')
    )->middleware('auth');
    Route::get('/plantillas/edit/{id}', array(
        'as' => 'plantillas.edit',
        'middleware' => 'permission:plantillas.edit',
        'uses' => 'PlantillasController@edit')
    )->middleware('auth');
    Route::post('/plantillas/update/{id}', array(
        'as' => 'plantillas.update',
        'middleware' => 'permission:plantillas.update',
        'uses' => 'PlantillasController@update')
    )->middleware('auth');
    Route::delete('/plantillas/destroy/{id}', array(
        'as' => 'plantillas.destroy',
        'middleware' => 'permission:plantillas.destroy',
        'uses' => 'PlantillasController@destroy')
    )->middleware('auth');
    Route::get('/plantillas/duplicate/{id}', array(
        'as' => 'plantillas.duplicate',
        'middleware' => 'permission:plantillas.duplicate',
        'uses' => 'PlantillasController@duplicate')
    )->middleware('auth');
    Route::get('/plantillas/ajaxFile', array(
        'as' => 'plantillas.ajaxFile',
        //'middleware' => 'permission:plantillas.duplicate',
        'uses' => 'PlantillasController@ajaxFile')
    )->middleware('auth');

    Route::get('/plantillas/eliminarEstatus', array(
        'as' => 'plantillas.eliminarEstatus',
        //'middleware' => 'permission:plantillas.duplicate',
        'uses' => 'PlantillasController@eliminarEstatus')
    )->middleware('auth');
    Route::get('/plantillas/eliminarEspecialidad', array(
        'as' => 'plantillas.eliminarEspecialidad',
        //'middleware' => 'permission:plantillas.duplicate',
        'uses' => 'PlantillasController@eliminarEspecialidad')
    )->middleware('auth');

    Route::group(['prefix' => 'filemanager','middleware' => 'auth'], function() {    
        Route::get('show', 'FilemanagerLaravelController@getShow');
        Route::get('connectors', 'FilemanagerLaravelController@getConnectors');
        Route::post('connectors', 'FilemanagerLaravelController@postConnectors');
    });

//Route::resource("nivels","NivelsController");// generated by scaffold - Nivel
//Route::get("nivels/nivel/{nivels}/duplicate", ['as' => 'nivels.duplicate', 'uses' => 'NivelsController@duplicate']);// generated by scaffold - Nivel

    Route::get('nivels/index', array(
        'as' => 'nivels.index',
        'middleware' => 'permission:nivels.index',
        'uses' => 'NivelsController@index')
    )->middleware('auth');

    Route::get('/nivels/create', array(
        'as' => 'nivels.create',
        'middleware' => 'permission:nivels.create',
        'uses' => 'NivelsController@create')
    )->middleware('auth');
    Route::post('nivels/store', array(
        'as' => 'nivels.store',
        'middleware' => 'permission:nivels.store',
        'uses' => 'NivelsController@store')
    )->middleware('auth');
    Route::get('/nivels/show/{id}', array(
        'as' => 'nivels.show',
        'middleware' => 'permission:nivels.show',
        'uses' => 'NivelsController@show')
    )->middleware('auth');
    Route::get('/nivels/edit/{id}', array(
        'as' => 'nivels.edit',
        'middleware' => 'permission:nivels.edit',
        'uses' => 'NivelsController@edit')
    )->middleware('auth');
    Route::post('/nivels/update/{id}', array(
        'as' => 'nivels.update',
        'middleware' => 'permission:nivels.update',
        'uses' => 'NivelsController@update')
    )->middleware('auth');
    Route::delete('/nivels/destroy/{id}', array(
        'as' => 'nivels.destroy',
        'middleware' => 'permission:nivels.destroy',
        'uses' => 'NivelsController@destroy')
    )->middleware('auth');
    Route::get('/nivels/duplicate/{id}', array(
        'as' => 'nivels.duplicate',
        'middleware' => 'permission:nivels.duplicate',
        'uses' => 'NivelsController@duplicate')
    )->middleware('auth');
    Route::get('/nivels/ajaxFile', array(
        'as' => 'nivels.ajaxFile',
        'middleware' => 'permission:nivels.duplicate',
        'uses' => 'NivelsController@ajaxFile')
    )->middleware('auth');
    Route::get('/getCmbGrados', array(
        'as' => 'nivels.getCmbGrados',
        //'middleware' => 'permission:tareas.show',
        'uses' => 'NivelsController@getCmbGrados')
    )->middleware('auth');
//Route::resource("grados","GradosController");// generated by scaffold - Grado
//Route::get("grados/grado/{grados}/duplicate", ['as' => 'grados.duplicate', 'uses' => 'GradosController@duplicate']);// generated by scaffold - Grado
    Route::get('grados/index', array(
        'as' => 'grados.index',
        'middleware' => 'permission:grados.index',
        'uses' => 'GradosController@index')
    )->middleware('auth');

    Route::get('/grados/create', array(
        'as' => 'grados.create',
        'middleware' => 'permission:grados.create',
        'uses' => 'GradosController@create')
    )->middleware('auth');
    Route::post('grados/store', array(
        'as' => 'grados.store',
        'middleware' => 'permission:grados.store',
        'uses' => 'GradosController@store')
    )->middleware('auth');
    Route::get('/grados/show/{id}', array(
        'as' => 'grados.show',
        'middleware' => 'permission:grados.show',
        'uses' => 'GradosController@show')
    )->middleware('auth');
    Route::get('/grados/edit/{id}', array(
        'as' => 'grados.edit',
        'middleware' => 'permission:grados.edit',
        'uses' => 'GradosController@edit')
    )->middleware('auth');
    Route::post('/grados/update/{id}', array(
        'as' => 'grados.update',
        'middleware' => 'permission:grados.update',
        'uses' => 'GradosController@update')
    )->middleware('auth');
    Route::delete('/grados/destroy/{id}', array(
        'as' => 'grados.destroy',
        'middleware' => 'permission:grados.destroy',
        'uses' => 'GradosController@destroy')
    )->middleware('auth');
    Route::get('/grados/duplicate/{id}', array(
        'as' => 'grados.duplicate',
        'middleware' => 'permission:grados.duplicate',
        'uses' => 'GradosController@duplicate')
    )->middleware('auth');
    Route::get('/grados/ajaxFile', array(
        'as' => 'grados.ajaxFile',
        'middleware' => 'permission:grados.duplicate',
        'uses' => 'GradosController@ajaxFile')
    )->middleware('auth');
//Route::resource("cursos","CursosController");// generated by scaffold - Curso
//Route::get("cursos/curso/{cursos}/duplicate", ['as' => 'cursos.duplicate', 'uses' => 'CursosController@duplicate']);// generated by scaffold - Curso
    Route::get('cursos/index', array(
        'as' => 'cursos.index',
        'middleware' => 'permission:cursos.index',
        'uses' => 'CursosController@index')
    )->middleware('auth');

    Route::get('/cursos/create', array(
        'as' => 'cursos.create',
        'middleware' => 'permission:cursos.create',
        'uses' => 'CursosController@create')
    )->middleware('auth');
    Route::post('cursos/store', array(
        'as' => 'cursos.store',
        'middleware' => 'permission:cursos.store',
        'uses' => 'CursosController@store')
    )->middleware('auth');
    Route::get('/cursos/show/{id}', array(
        'as' => 'cursos.show',
        'middleware' => 'permission:cursos.show',
        'uses' => 'CursosController@show')
    )->middleware('auth');
    Route::get('/cursos/edit/{id}', array(
        'as' => 'cursos.edit',
        'middleware' => 'permission:cursos.edit',
        'uses' => 'CursosController@edit')
    )->middleware('auth');
    Route::post('/cursos/update/{id}', array(
        'as' => 'cursos.update',
        'middleware' => 'permission:cursos.update',
        'uses' => 'CursosController@update')
    )->middleware('auth');
    Route::delete('/cursos/destroy/{id}', array(
        'as' => 'cursos.destroy',
        'middleware' => 'permission:cursos.destroy',
        'uses' => 'CursosController@destroy')
    )->middleware('auth');
    Route::get('/cursos/duplicate/{id}', array(
        'as' => 'cursos.duplicate',
        'middleware' => 'permission:cursos.duplicate',
        'uses' => 'CursosController@duplicate')
    )->middleware('auth');
    Route::get('/cursos/ajaxFile', array(
        'as' => 'cursos.ajaxFile',
        'middleware' => 'permission:cursos.duplicate',
        'uses' => 'CursosController@ajaxFile')
    )->middleware('auth');
    Route::get('/getCmbSubcursos', array(
        'as' => 'subcursos.getCmbSubcursos',
        //'middleware' => 'permission:tareas.show',
        'uses' => 'CursosController@getCmbSubcursos')
    )->middleware('auth');
//Route::resource("subcursos","SubcursosController");// generated by scaffold - Subcurso
//Route::get("subcursos/subcurso/{subcursos}/duplicate", ['as' => 'subcursos.duplicate', 'uses' => 'SubcursosController@duplicate']);// generated by scaffold - Subcurso
    Route::get('subcursos/index', array(
        'as' => 'subcursos.index',
        'middleware' => 'permission:subcursos.index',
        'uses' => 'SubcursosController@index')
    )->middleware('auth');

    Route::get('/subcursos/create', array(
        'as' => 'subcursos.create',
        'middleware' => 'permission:subcursos.create',
        'uses' => 'SubcursosController@create')
    )->middleware('auth');
    Route::post('subcursos/store', array(
        'as' => 'subcursos.store',
        'middleware' => 'permission:subcursos.store',
        'uses' => 'SubcursosController@store')
    )->middleware('auth');
    Route::get('/subcursos/show/{id}', array(
        'as' => 'subcursos.show',
        'middleware' => 'permission:subcursos.show',
        'uses' => 'SubcursosController@show')
    )->middleware('auth');
    Route::get('/subcursos/edit/{id}', array(
        'as' => 'subcursos.edit',
        'middleware' => 'permission:subcursos.edit',
        'uses' => 'SubcursosController@edit')
    )->middleware('auth');
    Route::post('/subcursos/update/{id}', array(
        'as' => 'subcursos.update',
        'middleware' => 'permission:subcursos.update',
        'uses' => 'SubcursosController@update')
    )->middleware('auth');
    Route::delete('/subcursos/destroy/{id}', array(
        'as' => 'subcursos.destroy',
        'middleware' => 'permission:subcursos.destroy',
        'uses' => 'SubcursosController@destroy')
    )->middleware('auth');
    Route::get('/subcursos/duplicate/{id}', array(
        'as' => 'subcursos.duplicate',
        'middleware' => 'permission:subcursos.duplicate',
        'uses' => 'SubcursosController@duplicate')
    )->middleware('auth');
    Route::get('/subcursos/ajaxFile', array(
        'as' => 'subcursos.ajaxFile',
        'middleware' => 'permission:subcursos.duplicate',
        'uses' => 'SubcursosController@ajaxFile')
    )->middleware('auth');
//Route::get("diplomados/diplomado/{diplomados}/duplicate", ['as' => 'diplomados.duplicate', 'uses' => 'DiplomadosController@duplicate']);// generated by scaffold - Diplomado
//Route::resource("diplomados","DiplomadosController");// generated by scaffold - Diplomado    
    Route::get('diplomados/index', array(
        'as' => 'diplomados.index',
        'middleware' => 'permission:diplomados.index',
        'uses' => 'DiplomadosController@index')
    )->middleware('auth');

    Route::get('/diplomados/create', array(
        'as' => 'diplomados.create',
        'middleware' => 'permission:diplomados.create',
        'uses' => 'DiplomadosController@create')
    )->middleware('auth');
    Route::post('diplomados/store', array(
        'as' => 'diplomados.store',
        'middleware' => 'permission:diplomados.store',
        'uses' => 'DiplomadosController@store')
    )->middleware('auth');
    Route::get('/diplomados/show/{id}', array(
        'as' => 'diplomados.show',
        'middleware' => 'permission:diplomados.show',
        'uses' => 'DiplomadosController@show')
    )->middleware('auth');
    Route::get('/diplomados/edit/{id}', array(
        'as' => 'diplomados.edit',
        'middleware' => 'permission:diplomados.edit',
        'uses' => 'DiplomadosController@edit')
    )->middleware('auth');
    Route::post('/diplomados/update/{id}', array(
        'as' => 'diplomados.update',
        'middleware' => 'permission:diplomados.update',
        'uses' => 'DiplomadosController@update')
    )->middleware('auth');
    Route::delete('/diplomados/destroy/{id}', array(
        'as' => 'diplomados.destroy',
        'middleware' => 'permission:diplomados.destroy',
        'uses' => 'DiplomadosController@destroy')
    )->middleware('auth');
    Route::get('/diplomados/duplicate/{id}', array(
        'as' => 'diplomados.duplicate',
        'middleware' => 'permission:diplomados.duplicate',
        'uses' => 'DiplomadosController@duplicate')
    )->middleware('auth');
    Route::get('/getCmbSubdiplomados', array(
        'as' => 'diplomados.getCmbSubdiplomados',
        //'middleware' => 'permission:tareas.show',
        'uses' => 'DiplomadosController@getCmbSubdiplomados')
    )->middleware('auth');
//Route::resource("otros","SubdiplomadosController");// generated by scaffold - Subdiplomado
//Route::get("subdiplomados/subdiplomado/{subdiplomados}/duplicate", ['as' => 'subdiplomados.duplicate', 'uses' => 'SubdiplomadosController@duplicate']);// generated by scaffold - Subdiplomado
    Route::get('subdiplomados/index', array(
        'as' => 'subdiplomados.index',
        'middleware' => 'permission:subdiplomados.index',
        'uses' => 'SubdiplomadosController@index')
    )->middleware('auth');

    Route::get('/subdiplomados/create', array(
        'as' => 'subdiplomados.create',
        'middleware' => 'permission:subdiplomados.create',
        'uses' => 'SubdiplomadosController@create')
    )->middleware('auth');
    Route::post('subdiplomados/store', array(
        'as' => 'subdiplomados.store',
        'middleware' => 'permission:subdiplomados.store',
        'uses' => 'SubdiplomadosController@store')
    )->middleware('auth');
    Route::get('/subdiplomados/show/{id}', array(
        'as' => 'subdiplomados.show',
        'middleware' => 'permission:subdiplomados.show',
        'uses' => 'SubdiplomadosController@show')
    )->middleware('auth');
    Route::get('/subdiplomados/edit/{id}', array(
        'as' => 'subdiplomados.edit',
        'middleware' => 'permission:subdiplomados.edit',
        'uses' => 'SubdiplomadosController@edit')
    )->middleware('auth');
    Route::post('/subdiplomados/update/{id}', array(
        'as' => 'subdiplomados.update',
        'middleware' => 'permission:subdiplomados.update',
        'uses' => 'SubdiplomadosController@update')
    )->middleware('auth');
    Route::delete('/subdiplomados/destroy/{id}', array(
        'as' => 'subdiplomados.destroy',
        'middleware' => 'permission:subdiplomados.destroy',
        'uses' => 'SubdiplomadosController@destroy')
    )->middleware('auth');
    Route::get('/subdiplomados/duplicate/{id}', array(
        'as' => 'subdiplomados.duplicate',
        'middleware' => 'permission:subdiplomados.duplicate',
        'uses' => 'SubdiplomadosController@duplicate')
    )->middleware('auth');
//Route::resource("otros","OtrosController");// generated by scaffold - Otro
//Route::get("otros/otro/{otros}/duplicate", ['as' => 'otros.duplicate', 'uses' => 'OtrosController@duplicate']);// generated by scaffold - Otro
    Route::get('otros/index', array(
        'as' => 'otros.index',
        'middleware' => 'permission:otros.index',
        'uses' => 'OtrosController@index')
    )->middleware('auth');

    Route::get('/otros/create', array(
        'as' => 'otros.create',
        'middleware' => 'permission:otros.create',
        'uses' => 'otrosController@create')
    )->middleware('auth');
    Route::post('otros/store', array(
        'as' => 'otros.store',
        'middleware' => 'permission:otros.store',
        'uses' => 'otrosController@store')
    )->middleware('auth');
    Route::get('/otros/show/{id}', array(
        'as' => 'otros.show',
        'middleware' => 'permission:otros.show',
        'uses' => 'OtrosController@show')
    )->middleware('auth');
    Route::get('/otros/edit/{id}', array(
        'as' => 'otros.edit',
        'middleware' => 'permission:otros.edit',
        'uses' => 'OtrosController@edit')
    )->middleware('auth');
    Route::post('/otros/update/{id}', array(
        'as' => 'otros.update',
        'middleware' => 'permission:otros.update',
        'uses' => 'otrosController@update')
    )->middleware('auth');
    Route::delete('/otros/destroy/{id}', array(
        'as' => 'otros.destroy',
        'middleware' => 'permission:otros.destroy',
        'uses' => 'OtrosController@destroy')
    )->middleware('auth');
    Route::get('/otros/duplicate/{id}', array(
        'as' => 'otros.duplicate',
        'middleware' => 'permission:otros.duplicate',
        'uses' => 'otrosController@duplicate')
    )->middleware('auth');
    Route::get('/getCmbSubotros', array(
        'as' => 'subotros.getCmbSubotros',
        //'middleware' => 'permission:tareas.show',
        'uses' => 'OtrosController@getCmbSubotros')
    )->middleware('auth');
//Route::resource("subotros","SubotrosController");// generated by scaffold - Subotro
//Route::get("subotros/subotro/{subotros}/duplicate", ['as' => 'subotros.duplicate', 'uses' => 'SubotrosController@duplicate']);// generated by scaffold - Subotro
    Route::get('subotros/index', array(
        'as' => 'subotros.index',
        'middleware' => 'permission:subotros.index',
        'uses' => 'SubotrosController@index')
    )->middleware('auth');

    Route::get('/subotros/create', array(
        'as' => 'subotros.create',
        'middleware' => 'permission:subotros.create',
        'uses' => 'SubotrosController@create')
    )->middleware('auth');
    Route::post('subotros/store', array(
        'as' => 'subotros.store',
        'middleware' => 'permission:subotros.store',
        'uses' => 'SubotrosController@store')
    )->middleware('auth');
    Route::get('/subotros/show/{id}', array(
        'as' => 'subotros.show',
        'middleware' => 'permission:subotros.show',
        'uses' => 'SubotrosController@show')
    )->middleware('auth');
    Route::get('/subotros/edit/{id}', array(
        'as' => 'subotros.edit',
        'middleware' => 'permission:subotros.edit',
        'uses' => 'SubotrosController@edit')
    )->middleware('auth');
    Route::post('/subotros/update/{id}', array(
        'as' => 'subotros.update',
        'middleware' => 'permission:subotros.update',
        'uses' => 'SubotrosController@update')
    )->middleware('auth');
    Route::delete('/subotros/destroy/{id}', array(
        'as' => 'subotros.destroy',
        'middleware' => 'permission:subotros.destroy',
        'uses' => 'SubotrosController@destroy')
    )->middleware('auth');
    Route::get('/subotros/duplicate/{id}', array(
        'as' => 'subotros.duplicate',
        'middleware' => 'permission:subotros.duplicate',
        'uses' => 'SubotrosController@duplicate')
    )->middleware('auth');
    
//Route::resource("promocions","PromocionsController");// generated by scaffold - Promocion
//Route::get("promocions/promocion/{promocions}/duplicate", ['as' => 'promocions.duplicate', 'uses' => 'PromocionsController@duplicate']);// generated by scaffold - Promocion
    Route::get('promocions/index', array(
        'as' => 'promocions.index',
        'middleware' => 'permission:promocions.index',
        'uses' => 'PromocionsController@index')
    )->middleware('auth');
    Route::get('/promocions/create', array(
        'as' => 'promocions.create',
        'middleware' => 'permission:promocions.create',
        'uses' => 'PromocionsController@create')
    )->middleware('auth');
    Route::post('promocions/store', array(
        'as' => 'promocions.store',
        'middleware' => 'permission:promocions.store',
        'uses' => 'PromocionsController@store')
    )->middleware('auth');
    Route::get('/promocions/show/{id}', array(
        'as' => 'promocions.show',
        'middleware' => 'permission:promocions.show',
        'uses' => 'PromocionsController@show')
    )->middleware('auth');
    Route::get('/promocions/edit/{id}', array(
        'as' => 'promocions.edit',
        'middleware' => 'permission:promocions.edit',
        'uses' => 'PromocionsController@edit')
    )->middleware('auth');
    Route::post('/promocions/update/{id}', array(
        'as' => 'promocions.update',
        'middleware' => 'permission:promocions.update',
        'uses' => 'PromocionsController@update')
    )->middleware('auth');
    Route::delete('/promocions/destroy/{id}', array(
        'as' => 'promocions.destroy',
        'middleware' => 'permission:promocions.destroy',
        'uses' => 'PromocionsController@destroy')
    )->middleware('auth');
    Route::get('/promocions/duplicate/{id}', array(
        'as' => 'promocions.duplicate',
        'middleware' => 'permission:promocions.duplicate',
        'uses' => 'PromocionsController@duplicate')
    )->middleware('auth');
Route::resource("tpoCorreos","TpoCorreosController");// generated by scaffold - TpoCorreo
Route::get("tpoCorreos/tpoCorreo/{tpoCorreos}/duplicate", ['as' => 'tpoCorreos.duplicate', 'uses' => 'TpoCorreosController@duplicate']);// generated by scaffold - TpoCorreo
Route::resource("sms","SmsController");// generated by scaffold - Sm
Route::get("sms/sm/{sms}/duplicate", ['as' => 'sms.duplicate', 'uses' => 'SmsController@duplicate']);// generated by scaffold - Sm
Route::resource("correos","CorreosController");// generated by scaffold - Correo
Route::get("correos/correo/{correos}/duplicate", ['as' => 'correos.duplicate', 'uses' => 'CorreosController@duplicate']);// generated by scaffold - Correo
Route::resource("params","ParamsController");// generated by scaffold - Param
Route::get("params/param/{params}/duplicate", ['as' => 'params.duplicate', 'uses' => 'ParamsController@duplicate']);// generated by scaffold - Param
//Route::resource("stTareas","StTareasController");// generated by scaffold - StTarea
//Route::get("stTareas/stTarea/{stTareas}/duplicate", ['as' => 'stTareas.duplicate', 'uses' => 'StTareasController@duplicate']);// generated by scaffold - StTarea
    Route::get('stTareas/index', array(
        'as' => 'stTareas.index',
        'middleware' => 'permission:stTareas.index',
        'uses' => 'StTareasController@index')
    )->middleware('auth');
    Route::get('/stTareas/create', array(
        'as' => 'stTareas.create',
        'middleware' => 'permission:stTareas.create',
        'uses' => 'StTareasController@create')
    )->middleware('auth');
    Route::post('stTareas/store', array(
        'as' => 'stTareas.store',
        'middleware' => 'permission:stTareas.store',
        'uses' => 'StTareasController@store')
    )->middleware('auth');
    Route::get('/stTareas/show/{id}', array(
        'as' => 'stTareas.show',
        'middleware' => 'permission:stTareas.show',
        'uses' => 'StTareasController@show')
    )->middleware('auth');
    Route::get('/stTareas/edit/{id}', array(
        'as' => 'stTareas.edit',
        'middleware' => 'permission:stTareas.edit',
        'uses' => 'StTareasController@edit')
    )->middleware('auth');
    Route::post('/stTareas/update/{id}', array(
        'as' => 'stTareas.update',
        'middleware' => 'permission:stTareas.update',
        'uses' => 'StTareasController@update')
    )->middleware('auth');
    Route::delete('/stTareas/destroy/{id}', array(
        'as' => 'stTareas.destroy',
        'middleware' => 'permission:stTareas.destroy',
        'uses' => 'StTareasController@destroy')
    )->middleware('auth');
    Route::get('/stTareas/duplicate/{id}', array(
        'as' => 'stTareas.duplicate',
        'middleware' => 'permission:stTareas.duplicate',
        'uses' => 'StTareasController@duplicate')
    )->middleware('auth');
//Route::resource("asignacionTareas","AsignacionTareasController");// generated by scaffold - AsignacionTarea
//Route::get("asignacionTareas/asignacionTarea/{asignacionTareas}/duplicate", ['as' => 'asignacionTareas.duplicate', 'uses' => 'AsignacionTareasController@duplicate']);// generated by scaffold - AsignacionTareaRoute::resource("seguimientoTareas","SeguimientoTareasController");// generated by scaffold - SeguimientoTarea
    Route::get('asignacionTareas/index', array(
        'as' => 'asignacionTareas.index',
        'middleware' => 'permission:asignacionTareas.index',
        'uses' => 'AsignacionTareasController@index')
    )->middleware('auth');
    Route::get('/asignacionTareas/create', array(
        'as' => 'asignacionTareas.create',
        'middleware' => 'permission:asignacionTareas.create',
        'uses' => 'AsignacionTareasController@create')
    )->middleware('auth');
    Route::post('asignacionTareas/store', array(
        'as' => 'asignacionTareas.store',
        'middleware' => 'permission:asignacionTareas.store',
        'uses' => 'AsignacionTareasController@store')
    )->middleware('auth');
    Route::get('/asignacionTareas/show/{id}', array(
        'as' => 'asignacionTareas.show',
        'middleware' => 'permission:asignacionTareas.show',
        'uses' => 'AsignacionTareasController@show')
    )->middleware('auth');
    Route::get('/asignacionTareas/seguimiento/{id}', array(
        'as' => 'asignacionTareas.seguimiento',
        'middleware' => 'permission:asignacionTareas.seguimiento',
        'uses' => 'AsignacionTareasController@seguimiento')
    )->middleware('auth');
    Route::get('/asignacionTareas/edit/{id}', array(
        'as' => 'asignacionTareas.edit',
        'middleware' => 'permission:asignacionTareas.edit',
        'uses' => 'AsignacionTareasController@edit')
    )->middleware('auth');
    Route::post('/asignacionTareas/update/{id}', array(
        'as' => 'asignacionTareas.update',
        'middleware' => 'permission:asignacionTareas.update',
        'uses' => 'AsignacionTareasController@update')
    )->middleware('auth');
    Route::delete('/asignacionTareas/destroy/{id}', array(
        'as' => 'asignacionTareas.destroy',
        'middleware' => 'permission:asignacionTareas.destroy',
        'uses' => 'AsignacionTareasController@destroy')
    )->middleware('auth');
    Route::get('/asignacionTareas/duplicate/{id}', array(
        'as' => 'asignacionTareas.duplicate',
        'middleware' => 'permission:asignacionTareas.duplicate',
        'uses' => 'AsignacionTareasController@duplicate')
    )->middleware('auth');
//Route::resource("asuntos","AsuntosController");// generated by scaffold - Asunto
//Route::get("asuntos/asunto/{asuntos}/duplicate", ['as' => 'asuntos.duplicate', 'uses' => 'AsuntosController@duplicate']);// generated by scaffold - Asunto
    Route::get('asuntos/index', array(
        'as' => 'asuntos.index',
        'middleware' => 'permission:asuntos.index',
        'uses' => 'AsuntosController@index')
    )->middleware('auth');
    Route::get('/asuntos/create', array(
        'as' => 'asuntos.create',
        'middleware' => 'permission:asuntos.create',
        'uses' => 'AsuntosController@create')
    )->middleware('auth');
    Route::post('asuntos/store', array(
        'as' => 'asuntos.store',
        'middleware' => 'permission:asuntos.store',
        'uses' => 'AsuntosController@store')
    )->middleware('auth');
    Route::get('/asuntos/show/{id}', array(
        'as' => 'asuntos.show',
        'middleware' => 'permission:asuntos.show',
        'uses' => 'AsuntosController@show')
    )->middleware('auth');
    Route::get('/asuntos/edit/{id}', array(
        'as' => 'asuntos.edit',
        'middleware' => 'permission:asuntos.edit',
        'uses' => 'AsuntosController@edit')
    )->middleware('auth');
    Route::post('/asuntos/update/{id}', array(
        'as' => 'asuntos.update',
        'middleware' => 'permission:asuntos.update',
        'uses' => 'AsuntosController@update')
    )->middleware('auth');
    Route::delete('/asuntos/destroy/{id}', array(
        'as' => 'asuntos.destroy',
        'middleware' => 'permission:asuntos.destroy',
        'uses' => 'AsuntosController@destroy')
    )->middleware('auth');
    Route::get('/asuntos/duplicate/{id}', array(
        'as' => 'asuntos.duplicate',
        'middleware' => 'permission:asuntos.duplicate',
        'uses' => 'AsuntosController@duplicate')
    )->middleware('auth');

//Route::resource("seguimientoTareas","SeguimientoTareasController");// generated by scaffold - AsignacionTarea
//Route::get("seguimientoTareas/seguimientoTarea/{seguimientoTareas}/duplicate", ['as' => 'seguimientoTareas.duplicate', 'uses' => 'SeguimientoTareasController@duplicate']);// generated by scaffold - SeguimientoTarea
    Route::get('seguimientoTareas/index', array(
        'as' => 'seguimientoTareas.index',
        'middleware' => 'permission:seguimientoTareas.index',
        'uses' => 'SeguimientoTareasController@index')
    )->middleware('auth');
    Route::get('/seguimientoTareas/create', array(
        'as' => 'seguimientoTareas.create',
        'middleware' => 'permission:seguimientoTareas.create',
        'uses' => 'SeguimientoTareasController@create')
    )->middleware('auth');
    Route::post('seguimientoTareas/store', array(
        'as' => 'seguimientoTareas.store',
        'middleware' => 'permission:seguimientoTareas.store',
        'uses' => 'SeguimientoTareasController@store')
    )->middleware('auth');
    Route::get('/seguimientoTareas/show/{id}', array(
        'as' => 'seguimientoTareas.show',
        'middleware' => 'permission:seguimientoTareas.show',
        'uses' => 'SeguimientoTareasController@show')
    )->middleware('auth');
    Route::get('/seguimientoTareas/edit/{id}', array(
        'as' => 'seguimientoTareas.edit',
        'middleware' => 'permission:seguimientoTareas.edit',
        'uses' => 'SeguimientoTareasController@edit')
    )->middleware('auth');
    Route::post('/seguimientoTareas/update/{id}', array(
        'as' => 'seguimientoTareas.update',
        'middleware' => 'permission:seguimientoTareas.update',
        'uses' => 'SeguimientoTareasController@update')
    )->middleware('auth');
    Route::delete('/seguimientoTareas/destroy/{id}', array(
        'as' => 'seguimientoTareas.destroy',
        'middleware' => 'permission:seguimientoTareas.destroy',
        'uses' => 'SeguimientoTareasController@destroy')
    )->middleware('auth');
    Route::get('/seguimientoTareas/duplicate/{id}', array(
        'as' => 'seguimientoTareas.duplicate',
        'middleware' => 'permission:seguimientoTareas.duplicate',
        'uses' => 'SeguimientoTareasController@duplicate')
    )->middleware('auth');
//Route::resource("especialidads","EspecialidadsController");// generated by scaffold - Especialidad
//Route::get("especialidads/especialidad/{especialidads}/duplicate", ['as' => 'especialidads.duplicate', 'uses' => 'EspecialidadsController@duplicate']);// generated by scaffold - Especialidad
    Route::get('especialidads/index', array(
        'as' => 'especialidads.index',
        'middleware' => 'permission:especialidads.index',
        'uses' => 'especialidadsController@index')
    )->middleware('auth');
    Route::get('/especialidads/create', array(
        'as' => 'especialidads.create',
        'middleware' => 'permission:especialidads.create',
        'uses' => 'especialidadsController@create')
    )->middleware('auth');
    Route::post('especialidads/store', array(
        'as' => 'especialidads.store',
        'middleware' => 'permission:especialidads.store',
        'uses' => 'especialidadsController@store')
    )->middleware('auth');
    Route::get('/especialidads/show/{id}', array(
        'as' => 'especialidads.show',
        'middleware' => 'permission:especialidads.show',
        'uses' => 'especialidadsController@show')
    )->middleware('auth');
    Route::get('/especialidads/edit/{id}', array(
        'as' => 'especialidads.edit',
        'middleware' => 'permission:especialidads.edit',
        'uses' => 'especialidadsController@edit')
    )->middleware('auth');
    Route::post('/especialidads/update/{id}', array(
        'as' => 'especialidads.update',
        'middleware' => 'permission:especialidads.update',
        'uses' => 'especialidadsController@update')
    )->middleware('auth');
    Route::delete('/especialidads/destroy/{id}', array(
        'as' => 'especialidads.destroy',
        'middleware' => 'permission:especialidads.destroy',
        'uses' => 'especialidadsController@destroy')
    )->middleware('auth');
    Route::get('/especialidads/duplicate/{id}', array(
        'as' => 'especialidads.duplicate',
        'middleware' => 'permission:especialidads.duplicate',
        'uses' => 'especialidadsController@duplicate')
    )->middleware('auth');
Route::resource("tpoPlantels","TpoPlantelsController");// generated by scaffold - TpoPlantel
Route::get("tpoPlantels/tpoPlantel/{tpoPlantels}/duplicate", ['as' => 'tpoPlantels.duplicate', 'uses' => 'TpoPlantelsController@duplicate']);// generated by scaffold - TpoPlantel

