<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class AsignacionTarea extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
        $this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - StCliente,Cliente
        $this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - StCliente,Cliente
		$this->addRelationApp( new \App\Asunto, 'name' );  // generated by relation command - Asunto,AsignacionTarea
		$this->addRelationApp( new \App\Tarea, 'name' );  // generated by relation command - Tarea,AsignacionTarea
		$this->addRelationApp( new \App\StTarea, 'name' );  // generated by relation command - StTarea,AsignacionTarea
    } 

	//Mass Assignment
	protected $fillable = ['cliente_id','empleado_id','tarea_id','asunto_id','detalle','st_tarea_id','observaciones','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	// generated by relation command - StCliente,Cliente - start
	public function cliente() {
		return $this->belongsTo('App\Cliente');
	}// end
	// generated by relation command - StCliente,Cliente - start
	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end
	
    protected $dates = ['deleted_at'];

	// generated by relation command - Asunto,AsignacionTarea - start
	public function asunto() {
		return $this->belongsTo('App\Asunto');
	}// end

	// generated by relation command - Tarea,AsignacionTarea - start
	public function tarea() {
		return $this->belongsTo('App\Tarea');
	}// end

	// generated by relation command - StTarea,AsignacionTarea - start
	public function stTarea() {
		return $this->belongsTo('App\StTarea');
	}// end

	public function seguimientos(){
		return $this->hasMany('App\SeguimientoTarea', 'asignacion_tarea_id', 'id');	
	}
	
}