<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Asunto extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['name','usu_alta_id','usu_mod_id','bnd_empresa'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Asunto,AsignacionTarea - start
	public function asignacionTareas() {
		return $this->hasMany('App\AsignacionTarea');
	}// end

	// generated by relation command - Asunto,AvisosInicio - start
	public function avisosInicios() {
		return $this->hasMany('App\AvisosInicio');
	}// end

	// generated by relation command - Asunto,AvisosEmpresa - start
	public function avisosEmpresas() {
		return $this->hasMany('App\AvisosEmpresa');
	}// end

	// generated by relation command - Asunto,TareasEmpresa - start
	public function tareasEmpresas() {
		return $this->hasMany('App\TareasEmpresa');
	}// end
}