<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class AvancesTicket extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Ticket, 'nombre_corto' );  // generated by relation command - Ticket,AvancesTicket
		$this->addRelationApp( new \App\User, 'name' );  // generated by relation command - Ticket,AvancesTicket
		$this->addRelationApp( new \App\StTicket, 'name' );  // generated by relation command - StTicket,AvancesTicket
    } 

	//Mass Assignment
	protected $fillable = ['ticket_id','detalle','asignado_a','st_ticket_id','usu_alta_id','usu_mod_id','bnd_notificacion', 'bnd_nota'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Ticket,AvancesTicket - start
	public function ticket() {
		return $this->belongsTo('App\Ticket');
	}// end

	// generated by relation command - StTicket,AvancesTicket - start
	public function stTicket() {
		return $this->belongsTo('App\StTicket');
	}// end

	// generated by relation command - AvancesTicket,ImagenesAvancesTicket - start
	public function imagenesAvancesTickets() {
		return $this->hasMany('App\ImagenesAvancesTicket');
	}// end
}