<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class AvisosEmpresa extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Empresa, 'razon_social' );  // generated by relation command - Empresa,AvisosEmpresa
		$this->addRelationApp( new \App\Asunto, 'name' );  // generated by relation command - Asunto,AvisosEmpresa
    } 

	//Mass Assignment
	protected $fillable = ['empresa_id','asunto_id','detalle','fecha','activo','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Empresa,AvisosEmpresa - start
	public function empresa() {
		return $this->belongsTo('App\Empresa');
	}// end

	// generated by relation command - Asunto,AvisosEmpresa - start
	public function asunto() {
		return $this->belongsTo('App\Asunto');
	}// end
}