<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class CalendarioEvaluacion extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Lectivo, 'name' );  // generated by relation command - Lectivo,CalendarioEvaluacion
		$this->addRelationApp( new \App\Ponderacion, 'name' );  // generated by relation command - Ponderacion,CalendarioEvaluacion
		$this->addRelationApp( new \App\CargaPonderacion, 'name' );  // generated by relation command - CargaPonderacion,CalendarioEvaluacion
    } 

	//Mass Assignment
	protected $fillable = ['lectivo_id','ponderacion_id','carga_ponderacion_id','v_inicio','v_fin','plantel_id','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Lectivo,CalendarioEvaluacion - start
	public function lectivo() {
		return $this->belongsTo('App\Lectivo');
	}// end

	// generated by relation command - Ponderacion,CalendarioEvaluacion - start
	public function ponderacion() {
		return $this->belongsTo('App\Ponderacion');
	}// end

	// generated by relation command - CargaPonderacion,CalendarioEvaluacion - start
	public function cargaPonderacion() {
		return $this->belongsTo('App\CargaPonderacion');
	}// end
        
        public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end
}