<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Calificacion extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
	}

	//Mass Assignment
	protected $fillable = ['hacademica_id', 'examen_id', 'calificacion', 'fecha', 'tpo_examen_id', 'reporte_bnd', 'usu_alta_id', 'usu_mod_id', 'acta_final_id', 'lectivo_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end

	public function actaFinal()
	{
		return $this->hasOne('App\ActaFinal', 'id', 'acta_final_id');
	} // end

	// generated by relation command - Plantel,Hacademica - start
	public function hacademica()
	{
		return $this->belongsTo('App\Hacademica');
	} // end

	// generated by relation command - Plantel,Hacademica - start
	public function tpoExamen()
	{
		return $this->belongsTo('App\TpoExamen', 'tpo_examen_id', 'id');
	} // end

	public function lectivo()
	{
		return $this->belongsTo('App\Lectivo');
	} // end

	protected $dates = ['deleted_at'];

	// generated by relation command - Calificacion,CalificacionPonderacion - start
	public function calificacionPonderacions()
	{
		return $this->hasMany('App\CalificacionPonderacion');
	} // end
}
