<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Captacion extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Medio, 'name' );  // generated by relation command - Medio,Captacion
    } 

	//Mass Assignment
	protected $fillable = ['plantel','nombre','nombre2','ape_paterno','ape_materno','mail','tel_cel','tel_fijo','pais','medio_id','usu_alta_id','usu_mod_id','comen_obs'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Medio,Captacion - start
	public function medio() {
		return $this->belongsTo('App\Medio');
	}// end
}