<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class CcuestionarioDato extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Ccuestionario, 'name' );  // generated by relation command - Ccuestionario,CcuestionarioDato
		$this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Cliente,CcuestionarioDato
                $this->addRelationApp( new \App\CuestionarioPregunta, 'name' );  // generated by relation command - Especialidad,Empresa
                $this->addRelationApp( new \App\CuestionarioRespuesta, 'name' );  // generated by relation command - Especialidad,Empresa
    } 

	//Mass Assignment
	protected $fillable = ['cliente_id','ccuestionario_id','ccuestionario_pregunta_id','ccuestionario_respuesta_id','clave','name','usu_mod_id','usu_alta_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Ccuestionario,CcuestionarioDato - start
	public function cuestionario() {
		return $this->belongsTo('App\Ccuestionario');
	}// end

         // generated by relation command - Plantel,Empresa - start
	public function pregunta() {
		return $this->belongsTo('App\CcuestionarioPregunta');
	}// end
        
        // generated by relation command - Plantel,Empresa - start
	public function respuesta() {
		return $this->belongsTo('App\CcuestionarioRespuesta');
	}// end
        
	// generated by relation command - Cliente,CcuestionarioDato - start
	public function cliente() {
		return $this->belongsTo('App\Cliente');
	}// end
}