<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class ComenMueble extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Mueble, 'id' );  // generated by relation command - Mueble,ComenMueble
		$this->addRelationApp( new \App\StMueble, 'name' );  // generated by relation command - StMueble,ComenMueble
    } 

	//Mass Assignment
	protected $fillable = ['mueble_id','st_mueble_id','obs','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Mueble,ComenMueble - start
	public function mueble() {
		return $this->belongsTo('App\Mueble');
	}// end

	// generated by relation command - StMueble,ComenMueble - start
	public function stMueble() {
		return $this->belongsTo('App\StMueble');
	}// end
}