<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class ConciliacionMultipago extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\CuentaP, 'name');  // generated by relation command - CuentaP,ConciliacionMultipago
	}

	//Mass Assignment
	protected $fillable = ['fecha_carga', 'archivo', 'registros', 'contador_ejecucion', 'usu_alta_id', 'usu_mod_id', 'fec_inicio', 'fec_fin', 'cuenta_p_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end


	protected $dates = ['deleted_at'];

	// generated by relation command - ConciliacionMultipago,ConciliacionMultiDetalle - start
	public function conciliacionMultiDetalles()
	{
		return $this->hasMany('App\ConciliacionMultiDetalle');
	} // end

	// generated by relation command - CuentaP,ConciliacionMultipago - start
	public function cuentaP()
	{
		return $this->belongsTo('App\CuentaP');
	} // end
}
