<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class CotizacionCurso extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\FormaPago, 'name' );  // generated by relation command - FormaPago,CotizacionCurso
		$this->addRelationApp( new \App\StCursoEmpresa, 'name' );  // generated by relation command - StCursoEmpresa,CotizacionCurso
		$this->addRelationApp( new \App\Empresa, '' );  // generated by relation command - Empresa,CotizacionCurso
    } 

	//Mass Assignment
	protected $fillable = ['no_coti','empresa_id','fecha','descuento','subtotal','descuento','iva','total',
                               'observaciones','usu_alta_id','usu_mod_id','st_curso_empresa_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - FormaPago,CotizacionCurso - start
	public function formaPago() {
		return $this->belongsTo('App\FormaPago');
	}// end

	// generated by relation command - StCursoEmpresa,CotizacionCurso - start
	public function stCursoEmpresa() {
		return $this->belongsTo('App\StCursoEmpresa');
	}// end

	// generated by relation command - Empresa,CotizacionCurso - start
	public function empresa() {
		return $this->belongsTo('App\Empresa');
	}// end

	// generated by relation command - CotizacionCurso,CotizacionLn - start
	public function cotizacionLns() {
		return $this->hasMany('App\CotizacionLn');
	}// end

	// generated by relation command - CotizacionCurso,FacturaCotizacion - start
	public function facturaCotizacions() {
		return $this->hasMany('App\FacturaCotizacion');
	}// end
}