<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class CotizacionLn extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\StCursoEmpresa, 'name' );  // generated by relation command - StCursoEmpresa,CotizacionLn
		$this->addRelationApp( new \App\CotizacionCurso, 'no_coti' );  // generated by relation command - CotizacionCurso,CotizacionLn
		$this->addRelationApp( new \App\CursosEmpresa, 'name' );  // generated by relation command - CursosEmpresa,CotizacionLn
		$this->addRelationApp( new \App\TipoPrecioCoti, 'name' );  // generated by relation command - TipoPrecioCoti,CotizacionLn
		$this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - Empleado,CotizacionLn
    } 

	//Mass Assignment
	protected $fillable = ['cotizacion_curso_id','consecutivo','cursos_empresa_id','tipo_precio_coti_id','cantidad',
                               'st_curso_empresa_id','precio','total','descuento','usu_alta_id','usu_mod_id','empleado_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - StCursoEmpresa,CotizacionLn - start
	public function stCursoEmpresa() {
		return $this->belongsTo('App\StCursoEmpresa');
	}// end

	// generated by relation command - CotizacionCurso,CotizacionLn - start
	public function cotizacionCurso() {
		return $this->belongsTo('App\CotizacionCurso');
	}// end

	// generated by relation command - CursosEmpresa,CotizacionLn - start
	public function cursosEmpresa() {
		return $this->belongsTo('App\CursosEmpresa');
	}// end

	// generated by relation command - TipoPrecioCoti,CotizacionLn - start
	public function tipoPrecioCoti() {
		return $this->belongsTo('App\TipoPrecioCoti');
	}// end

	// generated by relation command - Empleado,CotizacionLn - start
	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end
}