<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class CuentaP extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	protected $table = "cuenta_ps";

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
	}

	//Mass Assignment
	protected $fillable = ['name', 'clave', 'usu_alta_id', 'usu_mod_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end


	protected $dates = ['deleted_at'];

	// generated by relation command - CuentaP,Plantel - start
	public function plantels()
	{
		return $this->hasMany('App\Plantel');
	} // end

	// generated by relation command - CuentaP,SerieFolioSimplificado - start
	public function serieFolioSimplificados() {
		return $this->hasMany('App\SerieFolioSimplificado');
	}// end
}
