<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class CuentasEfectivo extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['name','clabe','no_cuenta','saldo_inicial','saldo_actualizado','fecha_saldo_inicial','usu_alta_id','usu_mod_id', 'bnd_banco','csc_efectivo'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - CuentasEfectivo,Egreso - start
	public function egresos() {
		return $this->hasMany('App\Egreso');
	}// end
        
        public function plantels() {
                return $this->belongsToMany('App\Plantel','cuentas_efectivo_plantels','cuentas_efectivo_id','plantel_id');
	}// end

	// generated by relation command - CuentasEfectivo,HCuentasEfectivo - start
	public function hCuentasEfectivos() {
		return $this->hasMany('App\HCuentasEfectivo');
	}// end
        
        
}