<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Empresa extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,Empresa
		$this->addRelationApp( new \App\Municipio, 'name' );  // generated by relation command - Municipio,Empresa
		$this->addRelationApp( new \App\Estado, 'name' );  // generated by relation command - Estado,Empresa
		$this->addRelationApp( new \App\Giro, 'name' );  // generated by relation command - Giro,Empresa
		$this->addRelationApp( new \App\Especialidad, 'name' );  // generated by relation command - Especialidad,Empresa
                $this->addRelationApp( new \App\Cuestionario, 'name' );  // generated by relation command - Especialidad,Empresa
		$this->addRelationApp( new \App\StEmpresa, 'name' );  // generated by relation command - StEmpresa,Empresa
                $this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - StEmpresa,Empresa
                
    } 

	//Mass Assignment
	protected $fillable = ['razon_social','nombre_contacto','tel_fijo','tel_cel','correo1','correo2','calle','no_int','no_ex','colonia','municipio_id',
                               'estado_id','cp','giro_id','plantel_id','especialidad_id','cuestionario_id','usu_alta_id','usu_mod_id','st_empresa_id',
                               'empleado_id','puesto'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Plantel,Empresa - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end

	// generated by relation command - Municipio,Empresa - start
	public function municipio() {
		return $this->belongsTo('App\Municipio');
	}// end

	// generated by relation command - Estado,Empresa - start
	public function estado() {
		return $this->belongsTo('App\Estado');
	}// end

	// generated by relation command - Giro,Empresa - start
	public function giro() {
		return $this->belongsTo('App\Giro');
	}// end
        
        public function cuestionario() {
		return $this->belongsTo('App\Cuestionario');
	}// end

	// generated by relation command - Especialidad,Empresa - start
	public function especialidad() {
		return $this->belongsTo('App\Especialidad');
	}// end
        
        public function actividades() {
		return $this->belongsToMany('App\ActividadEmpresa', 'actividad_empresas_empresas', 'empresa_id','actividad_empresa_id');
	}// end
        
        public function combinaciones() {
		return $this->hasMany('App\CombinacionEmpresa');
	}// end

	// generated by relation command - StEmpresa,Empresa - start
	public function stEmpresa() {
		return $this->belongsTo('App\StEmpresa');
	}// end
        
        // generated by relation command - StEmpresa,Empresa - start
	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end

	// generated by relation command - Empresa,AvisosEmpresa - start
	public function avisosEmpresas() {
		return $this->hasMany('App\AvisosEmpresa');
	}// end

	// generated by relation command - Empresa,TareasEmpresa - start
	public function tareasEmpresas() {
		return $this->hasMany('App\TareasEmpresa');
	}// end

	// generated by relation command - Empresa,CotizacionCurso - start
	public function cotizacionCursos() {
		return $this->hasMany('App\CotizacionCurso');
	}// end

	// generated by relation command - Empresa,Vinculacion - start
	public function vinculacions() {
		return $this->hasMany('App\Vinculacion');
	}// end
}