<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Estado extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;
    //protected $table = 'estados';

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['name','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	
    protected $dates = ['deleted_at'];

	// generated by relation command - Estado,Municipio - start
	public function municipios() {
		return $this->hasMany('App\Municipio');
	}// end

	// generated by relation command - Estado,Cliente - start
	public function clientes() {
		return $this->hasMany('App\Cliente');
	}// end

	// generated by relation command - Estado,Alumno - start
	public function alumnos() {
		return $this->hasMany('App\Alumno');
	}// end

	// generated by relation command - Estado,Empresa - start
	public function empresas() {
		return $this->hasMany('App\Empresa');
	}// end

	
}