<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class FacturaGeneral extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,FacturaGeneral
    } 

	//Mass Assignment
	protected $fillable = ['plantel_id','fec_inicio','fec_fin','uuid','xml','folio','serie','usu_alta_id','usu_mod_id','usu_eliminar_id','total','fecha_factura'. 'error_last'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Plantel,FacturaGeneral - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end

	// generated by relation command - FacturaGeneral,FacturaGeneralLinea - start
	public function facturaGeneralLineas() {
		return $this->hasMany('App\FacturaGeneralLinea');
	}// end
}