<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;


class FacturaG extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
	protected $table = 'factura_gs';

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\CuentasEfectivo, 'no_cuenta' );  // generated by relation command - CuentasEfectivo,FacturaG
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,FacturaG
    } 

	//Mass Assignment
	protected $fillable = ['cuentas_efectivo_id','serie','folio','fecha','tipo_comprobante','lugar_expedicion','exportacion','periodicidad','meses','anio','emisor_rfc','emisor_nombre','emisor_regimen_fiscal','usu_alta_id','usu_mod_id','plantel_id', 'suma_manual','diferencia_sumas'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	// generated by relation command - CuentasEfectivo,FacturaG - start
	public function cuentasEfectivo() {
		return $this->belongsTo('App\CuentasEfectivo');
	}// end

	// generated by relation command - FacturaG,FacturaGLinea - start
	public function facturaGLineas() {
		return $this->hasMany('App\FacturaGLinea');
	}// end

	// generated by relation command - Plantel,FacturaG - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end


}