<?php

namespace App;

use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormatoDgcft extends Model
{
    use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\Plantel, 'razon');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\SepGrupo, 'name');  // generated by relation command - StCliente,Cliente
	}

    protected $fillable = ['name', 'enlace_operativo','plantel','plantel_id','direccion','cct','especialidad',
    'grupo','fec_elaboracion','fec_inicio','fechas_emision','fec_fin','ciclo_escolar','fec_edad','duracion',
	'duracion_materias','horario','horario_inicio','horario_fin','cantidad_clientes',
    'clientes','control','control_parte_fija','control_inicio','escolaridad','beca','grados','materias','calificaciones','resultados','final',
	'directora_nombre','sceo_nombre','usu_alta_id', 'usu_mod_id','inicio_matricula','sep_grupo_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end

	public function plantelR()
	{
		return $this->hasOne('App\Plantel', 'id', 'plantel_id');
	} // end

	public function sepGrupo()
	{
		return $this->hasOne('App\SepGrupo', 'id', 'sep_grupo_id');
	} // end

    public function formatoDgcftDetalles()
	{
		return $this->hasMany('App\FormatoDgcftDetalle');
	} // end


	protected $dates = ['deleted_at'];

}
