<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Grado extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
        $this->addRelationApp( new \App\Nivel, 'name' );  // generated by relation command - Municipio,Cliente
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Area,Empleado
		$this->addRelationApp( new \App\Especialidad, 'name' );  // generated by relation command - Municipio,Cliente
    } 

	//Mass Assignment
	protected $fillable = ['nivel_id','name','especialidad_id', 'plantel_id','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	public function nivel() {
		return $this->belongsTo('App\Nivel');
	}// end
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end
	public function especialidad() {
		return $this->belongsTo('App\Especialidad');
	}// end
    protected $dates = ['deleted_at'];

	// generated by relation command - Grado,Alumno - start
	public function alumnos() {
		return $this->hasMany('App\Alumno');
	}// end

	// generated by relation command - Grado,PeriodoEstudio - start
	public function periodoEstudios() {
		return $this->hasMany('App\PeriodoEstudio');
	}// end

	// generated by relation command - Grado,Hacademica - start
	public function hacademicas() {
		return $this->hasMany('App\Hacademica');
	}// end


}