<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Hacademica extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Plantel,Hacademica
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,Hacademica
		$this->addRelationApp( new \App\Especialidad, 'name' );  // generated by relation command - Especialidad,Hacademica
		$this->addRelationApp( new \App\Nivel, 'name' );  // generated by relation command - Nivel,Hacademica
		$this->addRelationApp( new \App\Grado, 'name' );  // generated by relation command - Grado,Hacademica
		$this->addRelationApp( new \App\Grupo, 'name' );  // generated by relation command - Grupo,Hacademica
		$this->addRelationApp( new \App\Materium, 'name' );  // generated by relation command - Grupo,Hacademica
		$this->addRelationApp( new \App\StMateria, 'name' );  // generated by relation command - Grupo,Hacademica
		$this->addRelationApp( new \App\Lectivo, 'name' );  // generated by relation command - Lectivo,Hacademica
    } 

	//Mass Assignment
	protected $fillable = ['inscripcion_id','cliente_id','plantel_id','especialidad_id','nivel_id','grado_id','grupo_id','materium_id','st_materium_id','lectivo_id','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Plantel,Hacademica - start
	public function cliente() {
		return $this->belongsTo('App\Cliente', 'cliente_id', 'id');
	}// end

	// generated by relation command - Plantel,Hacademica - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end

	// generated by relation command - Especialidad,Hacademica - start
	public function especialidad() {
		return $this->belongsTo('App\Especialidad');
	}// end

	// generated by relation command - Nivel,Hacademica - start
	public function nivel() {
		return $this->belongsTo('App\Nivel');
	}// end

	// generated by relation command - Grado,Hacademica - start
	public function grado() {
		return $this->belongsTo('App\Grado');
	}// end

	// generated by relation command - Grupo,Hacademica - start
	public function grupo() {
		return $this->belongsTo('App\Grupo');
	}// end

	// generated by relation command - Grupo,Hacademica - start
	public function materia() {
		return $this->belongsTo('App\Materium', 'materium_id', 'id');
	}// end

	// generated by relation command - Grupo,Hacademica - start
	public function stMateria() {
		return $this->belongsTo('App\StMateria', 'st_materium_id', 'id');
	}// end

	// generated by relation command - Lectivo,Hacademica - start
	public function lectivo() {
		return $this->belongsTo('App\Lectivo');
	}// end

	// generated by relation command - Lectivo,Hacademica - start
	public function inscripcion() {
		return $this->belongsTo('App\Inscripcion');
	}// end

	public function calificaciones() {
		return $this->hasMany('App\Calificacion');
	}// end
}