<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class HistoriaCliente extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\EventoCliente, 'name' );  // generated by relation command - EventoCliente,HistoriaCliente
		$this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Cliente,HistoriaCliente
    } 

	//Mass Assignment
	protected $fillable = ['evento_cliente_id','descripcion','fecha','archivo','cliente_id','usu_alta_id','usu_mod_id','fec_vigencia','inscripcion_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - EventoCliente,HistoriaCliente - start
	public function eventoCliente() {
		return $this->belongsTo('App\EventoCliente');
	}// end

	// generated by relation command - Cliente,HistoriaCliente - start
	public function cliente() {
		return $this->belongsTo('App\Cliente');
	}// end
}