<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Historial extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\HistoriaEvento, 'name' );  // generated by relation command - HistoriaEvento,Historial
		$this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - Empleado,Historial
    } 

	//Mass Assignment
	protected $fillable = ['historia_evento_id','descripcion','fecha','archivo','empleado_id','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - HistoriaEvento,Historial - start
	public function historiaEvento() {
		return $this->belongsTo('App\HistoriaEvento');
	}// end

	// generated by relation command - Empleado,Historial - start
	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end
}