<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class ImagenesAvancesTicket extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\AvancesTicket, 'detalle' );  // generated by relation command - AvancesTicket,ImagenesAvancesTicket
    } 

	//Mass Assignment
	protected $fillable = ['avances_ticket_id','nombre','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - AvancesTicket,ImagenesAvancesTicket - start
	public function avancesTicket() {
		return $this->belongsTo('App\AvancesTicket');
	}// end
}