<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class IncidencesCliente extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Cliente,IncidencesCliente
		$this->addRelationApp( new \App\IncidenceCliente, 'name' );  // generated by relation command - IncidenceCliente,IncidencesCliente
    } 

	//Mass Assignment
	protected $fillable = ['cliente_id','incidence_cliente_id','detalle','fecha','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Cliente,IncidencesCliente - start
	public function cliente() {
		return $this->belongsTo('App\Cliente');
	}// end

	// generated by relation command - IncidenceCliente,IncidencesCliente - start
	public function incidenceCliente() {
		return $this->belongsTo('App\IncidenceCliente');
	}// end
}