<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class InventarioLevantamiento extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\InventarioLevantamientoSt, 'name' );  // generated by relation command - InventarioLevantamientoSt,InventarioLevantamiento
		$this->addRelationApp( new \App\PlantelInventario, 'name' );  // generated by relation command - PlantelInventario,InventarioLevantamiento
    } 

	//Mass Assignment
	protected $fillable = ['fecha','plantel_inventario_id','inventario_levantamiento_st_id','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

    protected $dates = ['deleted_at'];

	// generated by relation command - InventarioLevantamiento,Inventario - start
	public function inventarios() {
		return $this->hasMany('App\Inventario');
	}// end

	// generated by relation command - InventarioLevantamiento,InventarioObservacion - start
	public function inventarioObservacions() {
		return $this->hasMany('App\InventarioObservacion');
	}// end

	// generated by relation command - InventarioLevantamientoSt,InventarioLevantamiento - start
	public function inventarioLevantamientoSt() {
		return $this->belongsTo('App\InventarioLevantamientoSt');
	}// end

	// generated by relation command - PlantelInventario,InventarioLevantamiento - start
	public function plantelInventario() {
		return $this->belongsTo('App\PlantelInventario');
	}// end
}