<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class InventarioObservacion extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\InventarioLevantamiento, 'fecha' );  // generated by relation command - InventarioLevantamiento,InventarioObservacion
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,InventarioObservacion
    } 

	//Mass Assignment
	protected $fillable = ['inventario_levantamiento_id','plantel_id','observacion','usu_alta_id','usu_mod_id','plantel_inventario_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - InventarioLevantamiento,InventarioObservacion - start
	public function inventarioLevantamiento() {
		return $this->belongsTo('App\InventarioLevantamiento');
	}// end

	// generated by relation command - Plantel,InventarioObservacion - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end

	public function plantelInventario() {
		return $this->belongsTo('App\PlantelInventario');
	}// end
}