<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Inventario extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\InventarioLevantamiento, 'fecha' );  // generated by relation command - InventarioLevantamiento,Inventario
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,Inventario
		$this->addRelationApp( new \App\PlantelInventario, 'name' );  // generated by relation command - Plantel,Inventario
    } 

	//Mass Assignment 
	
	protected $fillable = ['plantel_id','area','escuela','tipo_inventario','ubicacion','cantidad','nombre','medida','marca','observaciones','existe_si','existe_no','estado_bueno','estado_malo','usu_alta_id','usu_mod_id','inventario_levantamiento_id','origen','plantel_inventario_id','no_inventario'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

    protected $dates = ['deleted_at'];

	// generated by relation command - InventarioLevantamiento,Inventario - start
	public function inventarioLevantamiento() {
		return $this->belongsTo('App\InventarioLevantamiento');
	}// end

	

	public function plantelInventario() {
		return $this->belongsTo('App\PlantelInventario');
	}// end
}