<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lead extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\StLead, 'name');  // generated by relation command - StLead,Lead
		$this->addRelationApp(new \App\Medio, 'name');  // generated by relation command - Medio,Lead
		$this->addRelationApp(new \App\Plantel, 'razon');  // generated by relation command - Medio,Lead
		$this->addRelationApp(new \App\CicloMatricula, 'name');  // generated by relation command - Medio,Lead
	}

	//Mass Assignment
	protected $fillable = [
		'nombre',
		'nombre2',
		'ape_paterno',
		'ape_materno',
		'tel_fijo',
		'tel_cel',
		'email',
		'medio_id',
		'ciclo_interesado',
		'observaciones',
		'st_lead_id',
		'usu_alta_id',
		'usu_mod_id',
		'contador_llamadas',
		'plantel_id',
		'ciclo_matricula_id'
	];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end


	protected $dates = ['deleted_at'];

	// generated by relation command - StLead,Lead - start
	public function stLead()
	{
		return $this->belongsTo('App\StLead');
	} // end

	// generated by relation command - Medio,Lead - start
	public function medio()
	{
		return $this->belongsTo('App\Medio');
	} // end

	public function plantel()
	{
		return $this->belongsTo('App\Plantel');
	} // end

	public function cicloMatricula()
	{
		return $this->belongsTo('App\CicloMatricula');
	} // end
}
