<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lectivo extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['name','activo','usu_alta_id','usu_mod_id', 'inicio', 'fin'];

    protected $dates = ['deleted_at'];

	// generated by relation command - Lectivo,Plantel - start
	public function plantels() {
		return $this->hasMany('App\Plantel');
	}// end
}