<?php

namespace App;

use App\Services\UploadService;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Material extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\Seccion, 'name');  // generated by relation command - Seccion,Material
	}

	//Mass Assignment
	protected $fillable = ['seccion_id', 'descripcion', 'archivo', 'fecha_disponibilidad', 'usu_alta_id', 'usu_mod_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end


	protected $dates = ['deleted_at'];

	// generated by relation command - Seccion,Material - start
	public function seccion()
	{
		return $this->belongsTo('App\Seccion');
	} // end

	public function getArchivoUrlAttribute()
	{
		return UploadService::urlFile($this->id . "/" . $this->archivo, "do_materials");
	}
}
