<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Mueble extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,Mueble
		$this->addRelationApp( new \App\Articulo, 'name' );  // generated by relation command - Articulo,Mueble
		$this->addRelationApp( new \App\UbicacionArt, 'ubicacion' );  // generated by relation command - UbicacionArt,Mueble
		$this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - Empleado,Mueble
		$this->addRelationApp( new \App\StMueble, 'name' );  // generated by relation command - StMueble,Mueble
		$this->addRelationApp( new \App\StMuebleUso, 'name' );  // generated by relation command - StMuebleUso,Mueble
    } 

	//Mass Assignment
	protected $fillable = ['plantel_id','articulo_id','fecha_alta','ubicacion_art_id','empleado_id','marca','modelo','no_serie','observaciones','st_mueble_id','st_mueble_uso_id','no_inv','usu_alta_id','usu_mod_id', 'costo'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Plantel,Mueble - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end

	// generated by relation command - Articulo,Mueble - start
	public function articulo() {
		return $this->belongsTo('App\Articulo');
	}// end

	// generated by relation command - UbicacionArt,Mueble - start
	public function ubicacionArt() {
		return $this->belongsTo('App\UbicacionArt');
	}// end

	// generated by relation command - Empleado,Mueble - start
	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end

	// generated by relation command - StMueble,Mueble - start
	public function stMueble() {
		return $this->belongsTo('App\StMueble');
	}// end

	// generated by relation command - StMuebleUso,Mueble - start
	public function stMuebleUso() {
		return $this->belongsTo('App\StMuebleUso');
	} // end

	public function getNoInv(){
		$relleno='000000';
		$numero=substr($relleno, 1, (strlen($relleno)-strlen($this->no_inv))).$this->no_inv;
		return $this->plantel->cve_plantel.$this->ubicacionArt->clave.$numero;
	}
}