<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Nivel extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Area,Empleado
		$this->addRelationApp( new \App\Especialidad, 'name' );  // generated by relation command - Area,Empleado
    } 

	//Mass Assignment
	protected $fillable = ['name', 'especialidad_id','plantel_id','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end
	public function grados() {
		return $this->hasMany('App\Grado');
	}// end

	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end
	public function especialidad() {
		return $this->belongsTo('App\Especialidad', 'especialidad_id', 'id');
	}// end
    protected $dates = ['deleted_at'];

	// generated by relation command - Nivel,Alumno - start
	public function alumnos() {
		return $this->hasMany('App\Alumno');
	}// end

	// generated by relation command - Nivel,PeriodoEstudio - start
	public function periodoEstudios() {
		return $this->hasMany('App\PeriodoEstudio');
	}// end

	// generated by relation command - Nivel,Hacademica - start
	public function hacademicas() {
		return $this->hasMany('App\Hacademica');
	}// end
}