<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;
use Venturecraft\Revisionable\RevisionableTrait;

class PeticionOpenpay extends Model
{

    use SoftDeletes;
    use RevisionableTrait;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    }

    //Mass Assignment
    protected $fillable = ['pago_id', 'cliente_id','forma_pago_id','pname','plast_name',
    'pphone_number','pemail',
    'pmethod','pamount','pdescription','psend_mail','pconfirm','predirect_url','ppreferencia',
    'porder_id','fecha_limite',
    'rid','rauthorization','rmethod','roperation_type','rtransaction_type','rstatus',
    'rconciliated','rcreation_date','roperation_date','rdescription','rerror_message','ramount',
    'rcurrency','rpayment_method_type','rpayment_method_bank','rpayment_method_agreement',
    'rpayment_method_clabe','rpayment_method_name',
    'rpayment_method_url','rpayment_method_barcode_url','rpayment_method_paybin_reference',
    'rpayment_method_barcode_paybin_url',
    'rpayment_method_reference','rcustomer','rorder_id','dispositivo','navegador',
    'contador_peticiones','usu_alta_id', 'usu_mod_id','bnd_pagado','notificacion_pagado',
    'use_3d_secure','token_3d_secure'];


    public function usu_alta()
    {
        return $this->hasOne('App\User', 'id', 'usu_alta_id');
    } // end

    public function usu_mod()
    {
        return $this->hasOne('App\User', 'id', 'usu_mod_id');
    } // end


    protected $dates = ['deleted_at'];

    // generated by relation command - Pago,PeticionMultipago - start
    public function pago()
    {
        return $this->belongsTo('App\Pago');
    } // end


	public function cliente()
    {
        return $this->belongsTo('App\Cliente');
    } // end


}
