<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;
use Venturecraft\Revisionable\RevisionableTrait;

class PeticionPaycode extends Model
{

    use SoftDeletes;
    use RevisionableTrait;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    }

    //Mass Assignment
    protected $fillable = [
        'pago_id',
        'cliente_id',
        'forma_pago_id',
        'pnum_cel',
        'pfisrt_name',
        'ppaternal_surname',
        'pmaternal_surname',
        'pconcept',
        'pamount',
        'rsuccess',
        'rdisplay_message',
        'rreference_number',
        'rtrack_code',
        'rtocken_card',
        'rtoken_error',
        'rmetadata',
        'usu_alta_id',
        'usu_mod_id',
        'bnd_pagado',
        'card_type',
        'result_code',
        'bnd_conciliado',
        'card_4_digits'
    ];


    public function usu_alta()
    {
        return $this->hasOne('App\User', 'id', 'usu_alta_id');
    } // end

    public function usu_mod()
    {
        return $this->hasOne('App\User', 'id', 'usu_mod_id');
    } // end


    protected $dates = ['deleted_at'];

    // generated by relation command - Pago,PeticionMultipago - start
    public function pago()
    {
        return $this->belongsTo('App\Pago');
    } // end


    public function cliente()
    {
        return $this->belongsTo('App\Cliente');
    } // end


}
