<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class PivotDocEmpleado extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
		$this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - Area,Empleado
		$this->addRelationApp( new \App\DocEmpleado, 'name' );  // generated by relation command - Area,Empleado
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['empleado_id','doc_empleado_id','archivo','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end
	public function docEmpleado() {
		return $this->belongsTo('App\DocEmpleado');
	}// end


    protected $dates = ['deleted_at'];
}