<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class PivotAvisoGralEmpleado extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Empleado, 'nombre' );  // generated by relation command - Area,Empleado
		$this->addRelationApp( new \App\AvisoGral, 'desc_corta' );  // generated by relation command - Area,Empleado		
    } 

	//Mass Assignment
	protected $fillable = ['aviso_gral_id','empleado_id', 'leido', 'enviado','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	// generated by relation command - StCliente,Cliente - start
	public function empleado() {
		return $this->belongsTo('App\Empleado');
	}// end
	// generated by relation command - StCliente,Cliente - start
	public function avisoGral() {
		return $this->belongsTo('App\AvisoGral');
	}// end

    protected $dates = ['deleted_at'];
}