<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class PlantillaEmpresaCond extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\PlantillaEmpresaCampo, 'campo' );  // generated by relation command - PlantillaEmpresaCampo,PlantillaEmpresaCond
		$this->addRelationApp( new \App\PlantillaEmpresa, 'nombre' );  // generated by relation command - PlantillaEmpresa,PlantillaEmpresaCond
    } 

	//Mass Assignment
	protected $fillable = ['plantilla_empresa_id','operador_condicion','plantilla_empresa_campo_id','signo_comparacion','valor_condicion','interpretacion','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - PlantillaEmpresaCampo,PlantillaEmpresaCond - start
	public function plantillaEmpresaCampo() {
		return $this->belongsTo('App\PlantillaEmpresaCampo');
	}// end

	// generated by relation command - PlantillaEmpresa,PlantillaEmpresaCond - start
	public function plantillaEmpresa() {
		return $this->belongsTo('App\PlantillaEmpresa');
	}// end
}