<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Plantilla extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
        $this->addRelationApp( new \App\StCliente, 'name' );  // generated by relation command - StCliente,Cliente
        $this->addRelationApp( new \App\Periodo, 'name' );  // generated by relation command - StCliente,Cliente
        $this->addRelationApp( new \App\TpoCorreo, 'name' );  // generated by relation command - StCliente,Cliente
        $this->addRelationApp( new \App\Nivel, 'name' );  // generated by relation command - StCliente,Cliente
		$this->addRelationApp( new \App\Especialidad, 'name' );  // generated by relation command - Especialidad,Plantilla
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Especialidad,Plantilla
    } 

	//Mass Assignment
	protected $fillable = ['nombre','asunto','para_nombre', 'tpo_correo_id','plantilla','st_cliente_id','periodo_id','dia','nivel_id', 'inicio', 'fin','usu_alta_id','usu_mod_id', 'activo_bnd', 'sms_bnd','mail_bnd','sms', 'especialidad_id', 'plantel_id', 'img1'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	// generated by relation command - StCliente,Cliente - start
	public function stCliente() {
		return $this->belongsTo('App\StCliente');
	}// end

	// generated by relation command - StCliente,Cliente - start
	public function periodo() {
		return $this->belongsTo('App\Periodo');
	}// end

	public function tpoCorreo() {
		return $this->belongsTo('App\TpoCorreo');
	}// end

	public function nivel() {
		return $this->belongsTo('App\Nivel');
	}// end

	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end

	public function estatus(){
		return $this->belongsToMany('App\StCliente', 'plantillas_estatus', 'plantilla_id', 'estatus_id');
	}
	public function especialidad(){
		return $this->belongsToMany('App\Especialidad', 'plantillas_especialidad', 'plantilla_id', 'especialidad_id');
	}

    protected $dates = ['deleted_at'];

	// generated by relation command - Especialidad,Plantilla - start
	/*public function especialidad() {
		return $this->belongsTo('App\Especialidad');
	}// end
	*/
}