<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Exception;
use Illuminate\Database\Eloquent\SoftDeletes;

class PlantillaEmpresa extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['plantilla','nombre','detalle','asunto','dia','img1','img2','activo_bnd','sms_bnd','mail_bnd','sms','inicio','fin','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

    protected $dates = ['deleted_at'];

	public function parsePlantilla($data)
	{
		$parsed = preg_replace_callback('/{{(.*?)}}/', function ($matches) use ($data) {
			list($shortCode, $index) = $matches;
			//dd($data);
			if (isset($data[$index])) {
				return $data[$index];
			} else {	
				throw new Exception("Shortcode {$shortCode} not found in template id {$this->id}", 1);
			}
		}, $this->plantilla);

		return $parsed;
	}

	// generated by relation command - PlantillaEmpresa,PlantillaEmpresaCond - start
	public function plantillaEmpresaConds() {
		return $this->hasMany('App\PlantillaEmpresaCond');
	}// end
}