<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class PreguntaCliente extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
        $this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Municipio,Cliente
        $this->addRelationApp( new \App\Preguntum, 'name' );  // generated by relation command - Municipio,Cliente
    } 

	//Mass Assignment
	protected $fillable = ['pregunta_id','cliente_id','respuesta','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

	public function cli() {
		return $this->belongsTo('App\Cliente', 'cliente_id', 'id');
	}// end

	public function pregunta() {
		return $this->hasOne('App\Preguntum', 'id', 'pregunta_id');
	}// end

    protected $dates = ['deleted_at'];
}