<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;


class SepCertificado extends Model
{
	use RelationManagerTrait, GetAllDataTrait;


	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\Plantel, 'razon');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Especialidad, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Nivel, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Grado, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Grupo, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Lectivo, 'name');  // generated by relation command - StCliente,Cliente
	}

	//Mass Assignment
	protected $fillable = [
		'plantel_id',
		'especialidad_id',
		'nivel_id',
		'grado_id',
		'lectivo_id',
		'grupo_id',
		'r_sep_cargo_id',
		'responsable_id',
		'id_carrera',
		'id_asignatura',
		'fecha_expedicion',
		'usu_mod_id',
		'usu_alta_id'
	];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end

	public function plantel()
	{
		return $this->belongsTo('App\Plantel', 'plantel_id', 'id');
	} // end

	public function especialidad()
	{
		return $this->belongsTo('App\Especialidad', 'especialidad_id', 'id');
	} // end

	public function nivel()
	{
		return $this->belongsTo('App\Nivel', 'nivel_id', 'id');
	} // end

	public function grado()
	{
		return $this->belongsTo('App\Grado', 'grado_id', 'id');
	} // end

	public function lectivo()
	{
		return $this->belongsTo('App\Lectivo', 'lectivo_id', 'id');
	} // end

	public function grupo()
	{
		return $this->belongsTo('App\Grupo', 'grupo_id', 'id');
	} // end

	public function responsable()
	{
		return $this->belongsTo('App\Empleado', 'responsable_id', 'id');
	} // end

	public function cargo()
	{
		return $this->belongsTo('App\SepCargo', 'r_sep_cargo_id', 'id');
	}

	public function lineas()
	{
		return $this->hasMany('App\SepCertificadoL', 'sep_certificado_id', 'id');
	}
}
