<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class SepTitulo extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\Plantel, 'razon');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Especialidad, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Nivel, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Grado, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Grupo, 'name');  // generated by relation command - StCliente,Cliente
		$this->addRelationApp(new \App\Lectivo, 'name');  // generated by relation command - StCliente,Cliente
	}

	//Mass Assignment
	protected $fillable = ['plantel_id', 'especialidad_id', 'nivel_id', 'grado_id', 'lectivo_id', 'grupo_id', 'r1_id', 'r1_sep_cargo_id', 'r1_titulo', 'r2_id', 'r2_sep_cargo_id', 'r2_titulo', 'usu_alta_id', 'usu_mod_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end

	public function plantel()
	{
		return $this->belongsTo('App\Plantel', 'plantel_id', 'id');
	} // end

	public function especialidad()
	{
		return $this->belongsTo('App\Especialidad', 'especialidad_id', 'id');
	} // end

	public function nivel()
	{
		return $this->belongsTo('App\Nivel', 'nivel_id', 'id');
	} // end

	public function grado()
	{
		return $this->belongsTo('App\Grado', 'grado_id', 'id');
	} // end

	public function lectivo()
	{
		return $this->belongsTo('App\Lectivo', 'lectivo_id', 'id');
	} // end

	public function grupo()
	{
		return $this->belongsTo('App\Grupo', 'grupo_id', 'id');
	} // end

	public function r1()
	{
		return $this->belongsTo('App\Empleado', 'r1_id', 'id');
	} // end

	public function r1Cargo()
	{
		return $this->belongsTo('App\SepCargo', 'r1_sep_cargo_id', 'id');
	}

	public function r2()
	{
		return $this->belongsTo('App\Empleado', 'r2_id', 'id');
	} // end

	public function r2Cargo()
	{
		return $this->belongsTo('App\SepCargo', 'r2_sep_cargo_id', 'id');
	}

	public function lineas()
	{
		return $this->hasMany('App\SepTituloL', 'sep_titulo_id', 'id');
	}

	protected $dates = ['deleted_at'];
}
