<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class SerieFolioSimplificado extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\CuentaP, 'name');  // generated by relation command - CuentaP,SerieFolioSimplificado
		//$this->addRelationApp(new \App\Mese, 'name');  // generated by relation command - CuentaP,SerieFolioSimplificado
	}

	//Mass Assignment
	protected $fillable = ['cuenta_p_id', 'serie', 'folio_inicial', 'folio_actual', 'anio', 'mese_id', 'bnd_activo', 'bnd_fiscal', 'usu_alta_id', 'usu_mod_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end


	protected $dates = ['deleted_at'];

	// generated by relation command - CuentaP,SerieFolioSimplificado - start
	public function cuentaP()
	{
		return $this->belongsTo('App\CuentaP');
	} // end

	public function mes1()
	{
		return $this->belongsTo('App\Mese', 'mese_id', 'id');
	} // end
}
