<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class SetyceLote extends Model
{
	use RelationManagerTrait, GetAllDataTrait;
	use SoftDeletes;

	public function __construct(array $attributes = array())
	{
		parent::__construct($attributes);
		$this->addRelationApp(new \App\TitulacionGrupo, 'name');  // generated by relation command - OpcionTitulacion,Titulacion
	}

	//Mass Assignment
	protected $fillable = ['setyce_id', 'name', 'clientes', 'titulacion_grupo_id', 'usu_alta_id', 'usu_mod_id'];

	public function usu_alta()
	{
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	} // end

	public function usu_mod()
	{
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	} // end

	public function titulacionGrupo()
	{
		return $this->hasOne('App\TitulacionGrupo', 'id', 'titulacion_grupo_id');
	} // end

	protected $dates = ['deleted_at'];
}
