<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class StCuestionario extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['name','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end

    protected $dates = ['deleted_at'];

	// generated by relation command - StCuestionario,Cuestionario - start
	public function cuestionarios() {
		return $this->hasMany('App\Cuestionario');
	}// end

	// generated by relation command - StCuestionario,Ccuestionario - start
	public function ccuestionarios() {
		return $this->hasMany('App\Ccuestionario');
	}// end
}