<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subotro extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
        $this->addRelationApp( new \App\Otro, 'name' );  // generated by relation command - StCliente,Cliente
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Area,Empleado
    } 

	//Mass Assignment
	protected $fillable = ['otro_id', 'plantel_id','name','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end
	public function otro() {
		return $this->belongsTo('App\Otro');
	}// end
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end


    protected $dates = ['deleted_at'];
}