<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class TitulacionDocumentacion extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Titulacion, 'id' );  // generated by relation command - Titulacion,TitulacionDocumentacion
		$this->addRelationApp( new \App\TitulacionDocumento, 'name' );  // generated by relation command - TitulacionDocumento,TitulacionDocumentacion
    } 

	//Mass Assignment
	protected $fillable = ['titulacion_id','titulacion_documento_id','archivo','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Titulacion,TitulacionDocumentacion - start
	public function titulacion() {
		return $this->belongsTo('App\Titulacion');
	}// end

	// generated by relation command - TitulacionDocumento,TitulacionDocumentacion - start
	public function titulacionDocumento() {
		return $this->belongsTo('App\TitulacionDocumento');
	}// end
}