<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Titulacion extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\OpcionTitulacion, 'name' );  // generated by relation command - OpcionTitulacion,Titulacion
		$this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Cliente,Titulacion
    } 

	//Mass Assignment
	protected $fillable = ['cliente_id','fec_inicio','opcion_titulacion_id','usu_alta_id','usu_mod_id','bnd_titulado'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - OpcionTitulacion,Titulacion - start
	public function opcionTitulacion() {
		return $this->belongsTo('App\OpcionTitulacion');
	}// end

	// generated by relation command - Titulacion,TitulacionIntento - start
	public function titulacionIntentos() {
		return $this->hasMany('App\TitulacionIntento');
	}// end

	// generated by relation command - Cliente,Titulacion - start
	public function cliente() {
		return $this->belongsTo('App\Cliente');
	}// end

	// generated by relation command - Titulacion,TitulacionDocumentacion - start
	public function titulacionDocumentacions() {
		return $this->hasMany('App\TitulacionDocumentacion');
	}// end
}