<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transference extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Plantel, 'razon' );  // generated by relation command - Plantel,Transference
    } 

	//Mass Assignment
	protected $fillable = ['origen_id','destino_id','monto','fecha','responsable_id','plantel_id','plantel_destino_id','motivo','usu_alta_id','usu_mod_id','archivo'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end
        
        public function origen() {
		return $this->hasOne('App\CuentasEfectivo', 'id', 'origen_id');
	}// end
        
        public function destino() {
		return $this->hasOne('App\CuentasEfectivo', 'id', 'destino_id');
	}// end
        
        public function responsable() {
		return $this->hasOne('App\Empleado', 'id', 'responsable_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Plantel,Transference - start
	public function plantel() {
		return $this->belongsTo('App\Plantel');
	}// end
        
        public function plantelDestino() {
		return $this->belongsTo('App\Plantel');
	}// end
}