<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\GetAllDataTrait;
use App\Traits\RelationManagerTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vinculacion extends Model
{
    use RelationManagerTrait,GetAllDataTrait;
    use SoftDeletes;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Cliente, 'nombre' );  // generated by relation command - Cliente,Vinculacion
    } 

	//Mass Assignment
	protected $fillable = ['cliente_id','lugar_practica','tel_fijo','nombre_contacto','mail_contacto','fec_inicio','fec_fin','bnd_constancia_entregada','usu_alta_id','usu_mod_id'];

	public function usu_alta() {
		return $this->hasOne('App\User', 'id', 'usu_alta_id');
	}// end

	public function usu_mod() {
		return $this->hasOne('App\User', 'id', 'usu_mod_id');
	}// end


    protected $dates = ['deleted_at'];

	// generated by relation command - Cliente,Vinculacion - start
	public function cliente() {
		return $this->belongsTo('App\Cliente');
	}// end

	// generated by relation command - Vinculacion,DocVinculacionVinculacion - start
	public function docVinculacionVinculacions() {
		return $this->hasMany('App\DocVinculacionVinculacion');
	}// end

	// generated by relation command - Vinculacion,VinculacionHora - start
	public function vinculacionHoras() {
		return $this->hasMany('App\VinculacionHora');
	}// end
}